// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:2:36
);

  wire [31:0] chan_t0_wdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:3:22
  wire        chan_t0_wvalid;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:4:23
  wire        chan_t0_wready;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:5:23
  wire [31:0] chan_t0_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:6:22
  wire        chan_t0_rvalid;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:7:23
  wire        chan_t0_rready;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:8:23
  wire        chan_t0_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:9:21
  wire        chan_t0_almost_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:10:28
  wire        chan_t0_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:11:22
  wire        chan_t0_almost_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:12:29
  wire [31:0] chan_t1_wdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:13:22
  wire        chan_t1_wvalid;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:14:23
  wire        chan_t1_wready;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:15:23
  wire [31:0] chan_t1_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:16:22
  wire        chan_t1_rvalid;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:17:23
  wire        chan_t1_rready;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:18:23
  wire        chan_t1_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:19:21
  wire        chan_t1_almost_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:20:28
  wire        chan_t1_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:21:22
  wire        chan_t1_almost_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:22:29
  wire        chan_t2_wdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:23:22
  wire        chan_t2_wvalid;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:24:23
  wire        chan_t2_wready;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:25:23
  wire        chan_t2_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:26:22
  wire        chan_t2_rvalid;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:27:23
  wire        chan_t2_rready;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:28:23
  wire        chan_t2_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:29:21
  wire        chan_t2_almost_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:30:28
  wire        chan_t2_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:31:22
  wire        chan_t2_almost_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:32:29
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(2), .ADDR_WIDTH(1), .COUNT_WIDTH(2), .LAST_PTR_VALUE(1), .DEPTH_COUNT_VALUE(2), .ALMOST_FULL_LEVEL(1), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(1), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t0_fifo (	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:35:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:34:10
    .wr_en        (chan_t0_wvalid),
    .wr_data      (chan_t0_wdata),
    .full         (chan_t0_full),
    .almost_full  (chan_t0_almost_full),
    .rd_en        (chan_t0_rready),
    .rd_data      (chan_t0_rdata),
    .empty        (chan_t0_empty),
    .almost_empty (chan_t0_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:35:5
  assign chan_t0_wready = ~chan_t0_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:36:10, :37:10, :38:5
  assign chan_t0_rvalid = ~chan_t0_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:39:10, :40:10, :41:5
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(4), .ADDR_WIDTH(2), .COUNT_WIDTH(3), .LAST_PTR_VALUE(3), .DEPTH_COUNT_VALUE(4), .ALMOST_FULL_LEVEL(3), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(3), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t1_fifo (	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:44:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:43:10
    .wr_en        (chan_t1_wvalid),
    .wr_data      (chan_t1_wdata),
    .full         (chan_t1_full),
    .almost_full  (chan_t1_almost_full),
    .rd_en        (chan_t1_rready),
    .rd_data      (chan_t1_rdata),
    .empty        (chan_t1_empty),
    .almost_empty (chan_t1_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:44:5
  assign chan_t1_wready = ~chan_t1_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:45:10, :46:10, :47:5
  assign chan_t1_rvalid = ~chan_t1_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:48:10, :49:10, :50:5
  mygo_fifo #(.DATA_WIDTH(1), .DEPTH(2), .ADDR_WIDTH(1), .COUNT_WIDTH(2), .LAST_PTR_VALUE(1), .DEPTH_COUNT_VALUE(2), .ALMOST_FULL_LEVEL(1), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(1), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t2_fifo (	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:53:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:52:11
    .wr_en        (chan_t2_wvalid),
    .wr_data      (chan_t2_wdata),
    .full         (chan_t2_full),
    .almost_full  (chan_t2_almost_full),
    .rd_en        (chan_t2_rready),
    .rd_data      (chan_t2_rdata),
    .empty        (chan_t2_empty),
    .almost_empty (chan_t2_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:53:5
  assign chan_t2_wready = ~chan_t2_full;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:54:11, :55:11, :56:5
  assign chan_t2_rvalid = ~chan_t2_empty;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:57:11, :58:11, :59:5
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:61:16
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:62:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:60:15, :63:7
  reg  [1:0]  state_reg4;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:69:19
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:70:5
    state_reg4 = 2'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:65:14, :71:7
  reg         recv_reg6;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:74:18
  reg         print_reg8;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:76:19
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:78:5
    print_reg8 = 1'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:77:14, :79:7
  assign chan_t2_rready = state_reg4 == 2'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:66:14, :73:11, :82:11, :83:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:86:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:87:7
      state_reg4 <= 2'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:65:14, :88:9
    else begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:87:7
      case (state_reg4)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:73:11, :90:9
        2'b00:
          state_reg4 <= 2'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:66:14, :92:11
        2'b01: begin
          if (chan_t2_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:84:11, :95:11
            recv_reg6 <= chan_t2_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:85:11, :96:13
            state_reg4 <= 2'h2;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:67:15, :97:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:95:11
            state_reg4 <= state_reg4;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:73:11, :99:13
        end
        2'b10: begin
          print_reg8 = recv_reg6;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:75:11, :103:11
          $write("finished is %0s\n", ((print_reg8) ? "true" : "false"));	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:81:25, :104:17, :105:11
          state_reg4 <= 2'h3;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:68:15, :106:11
        end
        2'b11:
          state_reg4 <= state_reg4;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:73:11, :109:11
        default:
          state_reg4 <= state_reg4;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:73:11, :112:11
      endcase	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:73:11, :90:9
    end
  end // always @(posedge)
  main__proc_filter filter_inst0 (	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:116:5
    .clk            (clk),
    .rst            (rst),
    .chan_t0_rdata  (chan_t0_rdata),
    .chan_t0_rvalid (chan_t0_rvalid),
    .chan_t0_rready (chan_t0_rready),
    .chan_t1_wdata  (chan_t1_wdata),
    .chan_t1_wvalid (chan_t1_wvalid),
    .chan_t1_wready (chan_t1_wready)
  );	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:116:5
  main__proc_sink sink_inst1 (	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:117:5
    .clk            (clk),
    .rst            (rst),
    .chan_t1_rdata  (chan_t1_rdata),
    .chan_t1_rvalid (chan_t1_rvalid),
    .chan_t1_rready (chan_t1_rready),
    .chan_t2_wdata  (chan_t2_wdata),
    .chan_t2_wvalid (chan_t2_wvalid),
    .chan_t2_wready (chan_t2_wready)
  );	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:117:5
  main__proc_source source_inst2 (	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:118:5
    .clk            (clk),
    .rst            (rst),
    .chan_t0_wdata  (chan_t0_wdata),
    .chan_t0_wvalid (chan_t0_wvalid),
    .chan_t0_wready (chan_t0_wready)
  );	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:118:5
endmodule

module main__proc_filter(	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:35
               rst,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:49
  inout [31:0] chan_t0_rdata,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:66
  inout        chan_t0_rvalid,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:94
               chan_t0_rready,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:122
  inout [31:0] chan_t1_wdata,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:150
  inout        chan_t1_wvalid,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:178
               chan_t1_wready	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:121:206
);

  reg  [4:0]  state_reg40;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:147:20
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:148:5
    state_reg40 = 5'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:130:14, :149:7
  reg  [31:0] recv_reg42;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:152:19
  reg  [31:0] recv_reg44;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:154:19
  reg  [31:0] phi_reg46;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:156:18
  reg  [31:0] phi_reg51;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:161:18
  wire        _GEN = state_reg40 == 5'h3;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:133:14, :151:10, :164:10
  wire        _GEN_0 = state_reg40 == 5'hE;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:144:15, :151:10, :165:11
  assign chan_t1_wvalid = _GEN | _GEN_0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:164:10, :165:11, :168:11, :169:5
  assign chan_t1_wdata = _GEN ? 32'h5 : _GEN_0 ? phi_reg51 : 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:122:15, :162:10, :164:10, :165:11, :170:17, :171:11, :172:11, :173:5
  assign chan_t0_rready = state_reg40 == 5'h1 | state_reg40 == 5'h8;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:131:14, :138:14, :151:10, :166:11, :167:11, :175:11, :176:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:179:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:180:7
      state_reg40 <= 5'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:130:14, :181:9
    else begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:180:7
      case (state_reg40)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :183:9
        5'b00000:
          state_reg40 <= 5'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:131:14, :185:11
        5'b00001: begin
          if (chan_t0_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:177:11, :188:11
            recv_reg42 <= chan_t0_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:178:11, :189:13
            state_reg40 <= 5'h2;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:132:14, :190:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:188:11
            state_reg40 <= state_reg40;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :192:13
        end
        5'b00010:
          state_reg40 <= 5'h3;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:133:14, :196:11
        5'b00011: begin
          if (chan_t1_wready)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:174:11, :199:11
            state_reg40 <= 5'h4;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:134:14, :200:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:199:11
            state_reg40 <= state_reg40;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :202:13
        end
        5'b00100: begin
          state_reg40 <= 5'h5;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:135:14, :206:11
          phi_reg46 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:123:15, :207:11
        end
        5'b00101: begin
          if (phi_reg46 < 32'h5)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:124:17, :157:10, :158:10, :210:11
            state_reg40 <= 5'h7;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:137:14, :211:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:210:11
            state_reg40 <= 5'h6;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:136:14, :213:13
        end
        5'b00110:
          state_reg40 <= 5'h10;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:146:16, :217:11
        5'b00111:
          state_reg40 <= 5'h8;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:138:14, :220:11
        5'b01000: begin
          if (chan_t0_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:177:11, :223:11
            recv_reg44 <= chan_t0_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:178:11, :224:13
            state_reg40 <= 5'h9;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:139:14, :225:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:223:11
            state_reg40 <= state_reg40;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :227:13
        end
        5'b01001: begin
          if (recv_reg44 == 32'h19700328)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:125:23, :155:10, :159:10, :231:11
            state_reg40 <= 5'hC;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:142:15, :232:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:231:11
            state_reg40 <= 5'hA;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:140:15, :234:13
        end
        5'b01010: begin
          if (recv_reg44 == 32'h19700101)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:129:23, :155:10, :160:10, :238:11
            state_reg40 <= 5'hB;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:141:15, :239:13
          else begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:238:11
            state_reg40 <= 5'hD;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:143:15, :241:13
            phi_reg51 <= recv_reg44;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:155:10, :242:13
          end
        end
        5'b01011: begin
          state_reg40 <= 5'hD;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:143:15, :246:11
          phi_reg51 <= 32'h20071224;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:127:23, :247:11
        end
        5'b01100: begin
          state_reg40 <= 5'hD;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:143:15, :250:11
          phi_reg51 <= 32'h20050823;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:126:23, :251:11
        end
        5'b01101:
          state_reg40 <= 5'hE;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:144:15, :254:11
        5'b01110: begin
          if (chan_t1_wready)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:174:11, :257:11
            state_reg40 <= 5'hF;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:145:15, :258:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:257:11
            state_reg40 <= state_reg40;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :260:13
        end
        5'b01111: begin
          state_reg40 <= 5'h5;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:135:14, :264:11
          phi_reg46 <= phi_reg46 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:128:15, :157:10, :163:10, :265:11
        end
        5'b10000:
          state_reg40 <= state_reg40;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :268:11
        default:
          state_reg40 <= state_reg40;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :271:11
      endcase	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:151:10, :183:9
    end
  end // always @(posedge)
endmodule

module main__proc_sink(	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:33
               rst,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:47
  inout [31:0] chan_t1_rdata,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:64
  inout        chan_t1_rvalid,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:92
               chan_t1_rready,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:120
               chan_t2_wdata,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:148
               chan_t2_wvalid,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:175
               chan_t2_wready	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:277:203
);

  reg  [3:0]  state_reg81;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:293:20
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:294:5
    state_reg81 = 4'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:282:14, :295:7
  reg  [31:0] recv_reg83;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:298:19
  reg  [31:0] recv_reg85;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:300:19
  reg  [31:0] print_reg87;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:302:20
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:304:5
    print_reg87 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:303:17, :305:7
  reg  [31:0] print_reg89;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:307:20
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:309:5
    print_reg89 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:308:17, :310:7
  reg  [31:0] phi_reg91;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:312:18
  wire        _GEN = state_reg81 == 4'h5;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:287:14, :297:10, :317:10
  assign chan_t2_wvalid = _GEN;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:317:10, :320:5
  assign chan_t2_wdata = _GEN;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:317:10, :322:5
  assign chan_t1_rready = state_reg81 == 4'h1 | state_reg81 == 4'h8;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:283:14, :290:15, :297:10, :318:10, :319:10, :324:11, :325:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:328:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:329:7
      state_reg81 <= 4'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:282:14, :330:9
    else begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:329:7
      case (state_reg81)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:297:10, :332:9
        4'b0000:
          state_reg81 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:283:14, :334:11
        4'b0001: begin
          if (chan_t1_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:326:11, :337:11
            recv_reg83 <= chan_t1_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:327:11, :338:13
            state_reg81 <= 4'h2;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:284:14, :339:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:337:11
            state_reg81 <= state_reg81;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:297:10, :341:13
        end
        4'b0010: begin
          state_reg81 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:285:14, :345:11
          phi_reg91 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:280:15, :346:11
        end
        4'b0011: begin
          if (phi_reg91 < 32'h5)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:281:15, :313:10, :314:10, :349:11
            state_reg81 <= 4'h7;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:289:14, :350:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:349:11
            state_reg81 <= 4'h4;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:286:14, :352:13
        end
        4'b0100:
          state_reg81 <= 4'h5;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:287:14, :356:11
        4'b0101: begin
          if (chan_t2_wready)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:323:10, :359:11
            state_reg81 <= 4'h6;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:288:14, :360:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:359:11
            state_reg81 <= state_reg81;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:297:10, :362:13
        end
        4'b0110:
          state_reg81 <= 4'hA;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:292:15, :366:11
        4'b0111:
          state_reg81 <= 4'h8;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:290:15, :369:11
        4'b1000: begin
          if (chan_t1_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:326:11, :372:11
            recv_reg85 <= chan_t1_rdata;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:327:11, :373:13
            state_reg81 <= 4'h9;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:291:15, :374:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:372:11
            state_reg81 <= state_reg81;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:297:10, :376:13
        end
        4'b1001: begin
          print_reg87 = phi_reg91;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:313:10, :380:11
          print_reg89 = recv_reg85;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:301:10, :382:11
          $write("output: count %0d got integer 0x%0x\n", print_reg87,
                  print_reg89);	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:316:25, :381:17, :383:17, :384:11
          state_reg81 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:285:14, :385:11
          phi_reg91 <= phi_reg91 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:278:15, :313:10, :315:10, :386:11
        end
        4'b1010:
          state_reg81 <= state_reg81;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:297:10, :389:11
        default:
          state_reg81 <= state_reg81;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:297:10, :392:11
      endcase	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:297:10, :332:9
    end
  end // always @(posedge)
endmodule

module main__proc_source(	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:398:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:398:35
               rst,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:398:49
  inout [31:0] chan_t0_wdata,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:398:66
  inout        chan_t0_wvalid,	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:398:94
               chan_t0_wready	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:398:122
);

  reg  [3:0]  state_reg128;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:420:21
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:421:5
    state_reg128 = 4'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:407:14, :422:7
  reg  [31:0] print_reg130;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:425:21
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:427:5
    print_reg130 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:426:17, :428:7
  reg  [31:0] print_reg132;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:430:21
  initial	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:432:5
    print_reg132 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:431:17, :433:7
  reg  [31:0] phi_reg134;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:435:19
  reg  [31:0] phi_reg139;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:440:19
  wire        _GEN = state_reg128 == 4'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:408:14, :424:10, :444:10
  wire        _GEN_0 = state_reg128 == 4'hA;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:417:15, :424:10, :445:10
  assign chan_t0_wvalid = _GEN | _GEN_0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:444:10, :445:10, :446:10, :447:5
  assign chan_t0_wdata = _GEN ? 32'h5 : _GEN_0 ? phi_reg139 : 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:399:15, :441:10, :444:10, :445:10, :448:17, :449:11, :450:11, :451:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:453:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:454:7
      state_reg128 <= 4'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:407:14, :455:9
    else begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:454:7
      case (state_reg128)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:424:10, :457:9
        4'b0000:
          state_reg128 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:408:14, :459:11
        4'b0001: begin
          if (chan_t0_wready)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:452:11, :462:11
            state_reg128 <= 4'h2;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:409:14, :463:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:462:11
            state_reg128 <= state_reg128;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:424:10, :465:13
        end
        4'b0010: begin
          state_reg128 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:410:14, :469:11
          phi_reg134 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:400:15, :470:11
        end
        4'b0011: begin
          if (phi_reg134 < 32'h5)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:401:17, :436:10, :437:10, :473:11
            state_reg128 <= 4'h5;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:412:14, :474:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:473:11
            state_reg128 <= 4'h4;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:411:14, :476:13
        end
        4'b0100:
          state_reg128 <= 4'hC;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:419:15, :480:11
        4'b0101: begin
          if (phi_reg134 == 32'h1)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:402:15, :436:10, :438:10, :483:11
            state_reg128 <= 4'h8;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:415:15, :484:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:483:11
            state_reg128 <= 4'h6;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:413:14, :486:13
        end
        4'b0110: begin
          if (phi_reg134 == 32'h2)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:406:15, :436:10, :439:10, :490:11
            state_reg128 <= 4'h7;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:414:14, :491:13
          else begin	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:490:11
            state_reg128 <= 4'h9;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:416:15, :493:13
            phi_reg139 <= phi_reg134;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:436:10, :494:13
          end
        end
        4'b0111: begin
          state_reg128 <= 4'h9;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:416:15, :498:11
          phi_reg139 <= 32'h19700101;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:404:23, :499:11
        end
        4'b1000: begin
          state_reg128 <= 4'h9;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:416:15, :502:11
          phi_reg139 <= 32'h19700328;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:403:23, :503:11
        end
        4'b1001:
          state_reg128 <= 4'hA;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:417:15, :506:11
        4'b1010: begin
          if (chan_t0_wready)	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:452:11, :509:11
            state_reg128 <= 4'hB;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:418:15, :510:13
          else	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:509:11
            state_reg128 <= state_reg128;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:424:10, :512:13
        end
        4'b1011: begin
          print_reg130 = phi_reg134;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:436:10, :516:11
          print_reg132 = phi_reg139;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:441:10, :518:11
          $write("input: count %0d sent integer 0x%0x\n", print_reg130,
                  print_reg132);	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:443:25, :517:17, :519:17, :520:11
          state_reg128 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:410:14, :521:11
          phi_reg134 <= phi_reg134 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:405:17, :436:10, :442:10, :522:11
        end
        4'b1100:
          state_reg128 <= state_reg128;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:424:10, :525:11
        default:
          state_reg128 <= state_reg128;	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:424:10, :528:11
      endcase	// /home/qinkejiu/mygo/tests/stages/pipeline1/.mygo-tmp/.mygo-circt-587568197/design.pipeline.mlir:424:10, :457:9
    end
  end // always @(posedge)
endmodule


module mygo_fifo #(
  parameter integer DATA_WIDTH = 32,
  parameter integer DEPTH = 1,
  parameter integer ADDR_WIDTH = 1,
  parameter integer COUNT_WIDTH = 1,
  parameter integer LAST_PTR_VALUE = 0,
  parameter integer DEPTH_COUNT_VALUE = 1,
  parameter integer ALMOST_FULL_LEVEL = 1,
  parameter integer ALMOST_EMPTY_LEVEL = 0,
  parameter integer ALMOST_FULL_COUNT_VALUE = 1,
  parameter integer ALMOST_EMPTY_COUNT_VALUE = 0,
  parameter bit USE_REGISTERED_READ = 1'b0,
  parameter bit ALMOST_EMPTY_USES_EMPTY = 1'b1,
  parameter bit ASYNC_RESET = 1'b0
) (
  input  wire                   clk,
  input  wire                   rst_n,
  input  wire                   wr_en,
  input  wire [DATA_WIDTH-1:0]  wr_data,
  output wire                   full,
  output wire                   almost_full,
  input  wire                   rd_en,
  output wire [DATA_WIDTH-1:0]  rd_data,
  output wire                   empty,
  output wire                   almost_empty
);

  localparam [ADDR_WIDTH-1:0] LAST_PTR = ADDR_WIDTH'(LAST_PTR_VALUE);
  localparam [COUNT_WIDTH-1:0] DEPTH_COUNT = COUNT_WIDTH'(DEPTH_COUNT_VALUE);
  localparam [COUNT_WIDTH-1:0] ALMOST_FULL_COUNT = COUNT_WIDTH'(ALMOST_FULL_COUNT_VALUE);
  localparam [COUNT_WIDTH-1:0] ALMOST_EMPTY_COUNT = COUNT_WIDTH'(ALMOST_EMPTY_COUNT_VALUE);

  reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];
  reg [ADDR_WIDTH-1:0] wr_ptr;
  reg [ADDR_WIDTH-1:0] rd_ptr;
  reg [COUNT_WIDTH-1:0] count;

  wire wr_fire = wr_en && !full;
  wire rd_fire = rd_en && !empty;
  wire [ADDR_WIDTH-1:0] wr_ptr_next = (wr_ptr == LAST_PTR) ? {ADDR_WIDTH{1'b0}} : (wr_ptr + 1'b1);
  wire [ADDR_WIDTH-1:0] rd_ptr_next = (rd_ptr == LAST_PTR) ? {ADDR_WIDTH{1'b0}} : (rd_ptr + 1'b1);

  assign full = (count == DEPTH_COUNT);
  assign empty = (count == {COUNT_WIDTH{1'b0}});
  assign almost_full = (count >= ALMOST_FULL_COUNT);
  assign almost_empty = (ALMOST_EMPTY_USES_EMPTY != 1'b0) ? empty : (count <= ALMOST_EMPTY_COUNT);

  generate
    if (USE_REGISTERED_READ != 1'b0) begin : gen_registered_read
      reg [DATA_WIDTH-1:0] rd_data_reg;
      assign rd_data = empty ? {DATA_WIDTH{1'b0}} : rd_data_reg;

      if (ASYNC_RESET != 1'b0) begin : gen_async_reset
        always @(posedge clk or negedge rst_n) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
            rd_data_reg <= {DATA_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
            if (empty && wr_fire) begin
              rd_data_reg <= wr_data;
            end else if (rd_fire) begin
              if (count > 1) begin
                rd_data_reg <= mem[rd_ptr_next];
              end else if (wr_fire) begin
                rd_data_reg <= wr_data;
              end else begin
                rd_data_reg <= {DATA_WIDTH{1'b0}};
              end
            end else if (!empty) begin
              rd_data_reg <= mem[rd_ptr];
            end
          end
        end
      end else begin : gen_sync_reset
        always @(posedge clk) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
            rd_data_reg <= {DATA_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
            if (empty && wr_fire) begin
              rd_data_reg <= wr_data;
            end else if (rd_fire) begin
              if (count > 1) begin
                rd_data_reg <= mem[rd_ptr_next];
              end else if (wr_fire) begin
                rd_data_reg <= wr_data;
              end else begin
                rd_data_reg <= {DATA_WIDTH{1'b0}};
              end
            end else if (!empty) begin
              rd_data_reg <= mem[rd_ptr];
            end
          end
        end
      end
    end else begin : gen_direct_read
      assign rd_data = empty ? {DATA_WIDTH{1'b0}} : mem[rd_ptr];

      if (ASYNC_RESET != 1'b0) begin : gen_async_reset
        always @(posedge clk or negedge rst_n) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
          end
        end
      end else begin : gen_sync_reset
        always @(posedge clk) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
          end
        end
      end
    end
  endgenerate
endmodule
