// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:2:36
);

  reg signed [31:0] Rcon0_0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:4:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:5:5
    Rcon0_0 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:3:15, :6:7
  reg signed [31:0] Rcon0_1;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:9:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:10:5
    Rcon0_1 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:8:17, :11:7
  reg signed [31:0] Rcon0_10;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:14:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:15:5
    Rcon0_10 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:13:17, :16:7
  reg signed [31:0] Rcon0_11;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:19:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:20:5
    Rcon0_11 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:18:17, :21:7
  reg signed [31:0] Rcon0_12;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:24:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:25:5
    Rcon0_12 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:23:17, :26:7
  reg signed [31:0] Rcon0_13;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:29:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:30:5
    Rcon0_13 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:28:17, :31:7
  reg signed [31:0] Rcon0_14;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:34:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:35:5
    Rcon0_14 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:33:17, :36:7
  reg signed [31:0] Rcon0_15;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:39:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:40:5
    Rcon0_15 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:38:17, :41:7
  reg signed [31:0] Rcon0_16;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:44:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:45:5
    Rcon0_16 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:43:17, :46:7
  reg signed [31:0] Rcon0_17;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:49:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:50:5
    Rcon0_17 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:48:17, :51:7
  reg signed [31:0] Rcon0_18;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:54:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:55:5
    Rcon0_18 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:53:17, :56:7
  reg signed [31:0] Rcon0_19;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:59:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:60:5
    Rcon0_19 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:58:18, :61:7
  reg signed [31:0] Rcon0_2;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:64:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:65:5
    Rcon0_2 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:63:18, :66:7
  reg signed [31:0] Rcon0_20;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:69:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:70:5
    Rcon0_20 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:68:18, :71:7
  reg signed [31:0] Rcon0_21;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:74:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:75:5
    Rcon0_21 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:73:18, :76:7
  reg signed [31:0] Rcon0_22;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:79:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:80:5
    Rcon0_22 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:78:18, :81:7
  reg signed [31:0] Rcon0_23;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:84:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:85:5
    Rcon0_23 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:83:18, :86:7
  reg signed [31:0] Rcon0_24;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:89:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:90:5
    Rcon0_24 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:88:18, :91:7
  reg signed [31:0] Rcon0_25;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:94:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:95:5
    Rcon0_25 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:93:18, :96:7
  reg signed [31:0] Rcon0_26;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:99:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:100:5
    Rcon0_26 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:98:18, :101:7
  reg signed [31:0] Rcon0_27;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:104:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:105:5
    Rcon0_27 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:103:18, :106:7
  reg signed [31:0] Rcon0_28;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:109:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:110:5
    Rcon0_28 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:108:18, :111:7
  reg signed [31:0] Rcon0_29;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:114:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:115:5
    Rcon0_29 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:113:18, :116:7
  reg signed [31:0] Rcon0_3;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:119:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:120:5
    Rcon0_3 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:118:18, :121:7
  reg signed [31:0] Rcon0_4;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:124:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:125:5
    Rcon0_4 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:123:18, :126:7
  reg signed [31:0] Rcon0_5;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:129:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:130:5
    Rcon0_5 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:128:18, :131:7
  reg signed [31:0] Rcon0_6;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:134:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:135:5
    Rcon0_6 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:133:18, :136:7
  reg signed [31:0] Rcon0_7;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:139:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:140:5
    Rcon0_7 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:138:18, :141:7
  reg signed [31:0] Rcon0_8;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:144:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:145:5
    Rcon0_8 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:143:18, :146:7
  reg signed [31:0] Rcon0_9;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:149:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:150:5
    Rcon0_9 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:148:18, :151:7
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:154:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:155:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:153:18, :156:7
  reg        state_reg2;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:160:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:161:5
    state_reg2 = 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:158:14, :162:7
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:166:5
    if (rst)	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:167:7
      state_reg2 <= 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:158:14, :168:9
    else begin	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:167:7
      case (state_reg2)	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:164:10, :170:9
        1'b0: begin
          $write("encrypted message \t3925841d02dc09fbdc118597196a0b32\n");	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:165:25, :172:11
          $write("decrypto message\t3243f6a8885a308d313198a2e0370734\n\n0\n");	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:165:25, :173:11
          state_reg2 <= 1'h1;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:159:13, :174:11
        end
        1'b1:
          state_reg2 <= state_reg2;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:164:10, :177:11
        default:
          state_reg2 <= state_reg2;	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:164:10, :180:11
      endcase	// /home/qinkejiu/mygo/tests/CHStone/aes/.mygo-tmp/.mygo-circt-1715893716/design.pipeline.mlir:164:10, :170:9
    end
  end // always @(posedge)
endmodule

