// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:2:36
);

  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:4:16
  initial	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:5:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:3:15, :6:7
  wire [31:0] _GEN = 32'h1;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:8:15
  wire [15:0] _GEN_0 = 16'h2;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:9:15
  reg         state_reg4;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:12:19
  initial	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:13:5
    state_reg4 = 1'h0;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:10:14, :14:7
  reg signed [63:0] print_reg6;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:17:19
  initial	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:19:5
    print_reg6 = 64'h0;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:18:15, :20:7
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:30:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:31:7
      state_reg4 <= 1'h0;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:10:14, :32:9
    else begin	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:31:7
      case (state_reg4)	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:16:10, :34:9
        1'b0: begin
          print_reg6 = {{32{_GEN[31]}}, _GEN} + {{48{_GEN_0[15]}}, _GEN_0};	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:8:15, :9:15, :22:10, :23:10, :24:10, :25:10, :26:10, :27:10, :28:10, :36:11
          $write("The result is small: %0d\n", print_reg6);	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:29:25, :37:16, :38:11
          state_reg4 <= 1'h1;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:11:13, :39:11
        end
        1'b1:
          state_reg4 <= state_reg4;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:16:10, :42:11
        default:
          state_reg4 <= state_reg4;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:16:10, :45:11
      endcase	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-3865173215/design.pipeline.mlir:16:10, :34:9
    end
  end // always @(posedge)
endmodule

