// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-1248736797/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-1248736797/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-1248736797/design.pipeline.mlir:2:36
);

  wire [31:0] _GEN = 32'h1;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-1248736797/design.pipeline.mlir:3:15
  wire [15:0] _GEN_0 = 16'h2;	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-1248736797/design.pipeline.mlir:4:15
  always @(posedge clk)	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-1248736797/design.pipeline.mlir:13:5
    $fwrite(32'h80000001, "The result is small: %d\n",
            $signed({{32{_GEN[31]}}, _GEN} + {{48{_GEN_0[15]}}, _GEN_0}));	// /home/qinkejiu/mygo/tests/stages/simple/.mygo-tmp/.mygo-circt-1248736797/design.pipeline.mlir:3:15, :4:15, :5:10, :6:10, :7:10, :8:10, :9:10, :10:10, :11:10, :12:25, :14:7
endmodule

