// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:3
  input        clk,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:22
               rst,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:36
  input [63:0] test_in_0,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:50
               test_in_1,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:71
               test_in_2,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:92
               test_in_3,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:113
               test_in_4,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:134
               test_in_5,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:155
               test_in_6,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:176
               test_in_7,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:197
               test_in_8,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:218
               test_in_9,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:239
               test_in_10,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:260
               test_in_11,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:282
               test_in_12,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:304
               test_in_13,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:326
               test_in_14,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:348
               test_in_15,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:370
               test_in_16,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:392
               test_in_17,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:414
               test_in_18,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:436
               test_in_19,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:458
               test_in_20,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:480
               test_in_21,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:502
               test_in_22,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:524
               test_in_23,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:546
               test_in_24,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:568
               test_in_25,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:590
               test_in_26,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:612
               test_in_27,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:634
               test_in_28,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:656
               test_in_29,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:678
               test_in_30,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:700
               test_in_31,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:722
               test_in_32,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:744
               test_in_33,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:766
               test_in_34,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:788
               test_in_35,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:810
               test_out_0,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:832
               test_out_1,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:854
               test_out_2,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:876
               test_out_3,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:898
               test_out_4,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:920
               test_out_5,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:942
               test_out_6,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:964
               test_out_7,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:986
               test_out_8,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1008
               test_out_9,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1030
               test_out_10,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1052
               test_out_11,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1075
               test_out_12,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1098
               test_out_13,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1121
               test_out_14,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1144
               test_out_15,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1167
               test_out_16,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1190
               test_out_17,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1213
               test_out_18,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1236
               test_out_19,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1259
               test_out_20,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1282
               test_out_21,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1305
               test_out_22,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1328
               test_out_23,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1351
               test_out_24,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1374
               test_out_25,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1397
               test_out_26,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1420
               test_out_27,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1443
               test_out_28,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1466
               test_out_29,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1489
               test_out_30,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1512
               test_out_31,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1535
               test_out_32,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1558
               test_out_33,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1581
               test_out_34,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1604
               test_out_35	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:2:1627
);

  reg [2:0]  state_reg224;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:227:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:228:5
    state_reg224 = 3'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:220:14, :229:7
  reg signed [31:0] phi_reg226;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:232:19
  reg [31:0] phi_reg228;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:234:19
  reg [31:0] phi_reg374;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:380:19
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:524:5
    if (rst)	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:525:7
      state_reg224 <= 3'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:220:14, :526:9
    else begin	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:525:7
      case (state_reg224)	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:231:10, :528:9
        3'b000: begin
          state_reg224 <= 3'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:221:14, :530:11
          phi_reg226 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:210:15, :531:11
          phi_reg228 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:212:19, :532:11
        end
        3'b001: begin
          if ($signed(phi_reg228) < 32'sh24)	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:213:16, :235:10, :236:10, :535:11
            state_reg224 <= 3'h3;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:223:14, :536:13
          else	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:535:11
            state_reg224 <= 3'h2;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:222:14, :538:13
        end
        3'b010: begin
          $fwrite(32'h80000001, "%d\n", phi_reg226);	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:233:10, :523:25, :542:11
          state_reg224 <= 3'h6;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:226:15, :543:11
        end
        3'b011: begin
          if (64'h0 != (phi_reg228 == 32'h23
                          ? 64'hBFC63A23C48863DD
                          : phi_reg228 == 32'h22
                              ? 64'hBFD5E3AD0A69CAF7
                              : phi_reg228 == 32'h21
                                  ? 64'hBFE000021D0CA30D
                                  : phi_reg228 == 32'h20
                                      ? 64'hBFE491B9CD1B5D56
                                      : phi_reg228 == 32'h1F
                                          ? 64'hBFE883716E6FD781
                                          : phi_reg228 == 32'h1E
                                              ? 64'hBFEBB67C2C31CB4A
                                              : phi_reg228 == 32'h1D
                                                  ? 64'hBFEE11F7112DAE27
                                                  : phi_reg228 == 32'h1C
                                                      ? 64'hBFEF838B5EA2E7EA
                                                      : phi_reg228 == 32'h1B
                                                          ? 64'hBFEFFFFFC2E5DC8F
                                                          : phi_reg228 == 32'h1A
                                                              ? 64'hBFEF838B1AC64AFC
                                                              : phi_reg228 == 32'h19
                                                                  ? 64'hBFEE11F5912D2157
                                                                  : phi_reg228 == 32'h18
                                                                      ? 64'hBFEBB67A740AAE32
                                                                      : phi_reg228 == 32'h17
                                                                          ? 64'hBFE8836EB2DCF815
                                                                          : phi_reg228 == 32'h16
                                                                              ? 64'hBFE491B61CB9A3D3
                                                                              : phi_reg228 == 32'h15
                                                                                  ? 64'hBFDFFFFD494CF96B
                                                                                  : phi_reg228 == 32'h14
                                                                                      ? 64'hBFD5E3A4E68F8F3E
                                                                                      : phi_reg228 == 32'h13
                                                                                          ? 64'hBFC63A1444DDB37C
                                                                                          : phi_reg228 == 32'h12
                                                                                              ? 64'h3EA6AEDFFC454B91
                                                                                              : phi_reg228 == 32'h11
                                                                                                  ? 64'h3FC63A1D2189552C
                                                                                                  : phi_reg228 == 32'h10
                                                                                                      ? 64'h3FD5E3AA4E0590C5
                                                                                                      : phi_reg228 == 32'hF
                                                                                                          ? 64'h3FE00000EA5F43C8
                                                                                                          : phi_reg228 == 32'hE
                                                                                                              ? 64'h3FE491B81D72D8E8
                                                                                                              : phi_reg228 == 32'hD
                                                                                                                  ? 64'h3FE883709D4EA869
                                                                                                                  : phi_reg228 == 32'hC
                                                                                                                      ? 64'h3FEBB67B77C0142D
                                                                                                                      : phi_reg228 == 32'hB
                                                                                                                          ? 64'h3FEE11F692D962B4
                                                                                                                          : phi_reg228 == 32'hA
                                                                                                                              ? 64'h3FEF838BB0147989
                                                                                                                              : phi_reg228 == 32'h9
                                                                                                                                  ? 64'h3FEFFFFFE1CBD7AA
                                                                                                                                  : phi_reg228 == 32'h8
                                                                                                                                      ? 64'h3FEF838B6ADFFAC0
                                                                                                                                      : phi_reg228 == 32'h7
                                                                                                                                          ? 64'h3FEE11F6127E28AD
                                                                                                                                          : phi_reg228 == 32'h6
                                                                                                                                              ? 64'h3FEBB67AC40B2BED
                                                                                                                                              : phi_reg228 == 32'h5
                                                                                                                                                  ? 64'h3FE8836F672614A6
                                                                                                                                                  : phi_reg228 == 32'h4
                                                                                                                                                      ? 64'h3FE491B716C242E3
                                                                                                                                                      : phi_reg228 == 32'h3
                                                                                                                                                          ? 64'h3FDFFFFF91F9AA91
                                                                                                                                                          : phi_reg228 == 32'h2
                                                                                                                                                              ? 64'h3FD5E3A82B09BF3E
                                                                                                                                                              : phi_reg228 == 32'h1
                                                                                                                                                                  ? 64'h3FC63A1A335AADCD
                                                                                                                                                                  : 64'h0))	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:43:15, :44:15, :45:15, :47:15, :48:15, :49:17, :51:17, :52:17, :53:17, :55:18, :56:18, :57:18, :58:18, :60:18, :61:18, :62:19, :64:19, :65:19, :66:19, :68:19, :69:19, :70:19, :71:19, :73:19, :74:19, :75:19, :77:19, :78:19, :79:19, :81:19, :82:19, :83:19, :84:19, :86:19, :87:19, :133:18, :137:33, :141:33, :146:33, :150:33, :154:33, :159:33, :163:33, :167:33, :172:33, :177:33, :181:33, :183:33, :185:33, :186:33, :187:33, :188:33, :189:33, :190:33, :191:34, :193:34, :194:34, :195:34, :196:34, :197:34, :198:34, :199:34, :200:34, :201:34, :202:34, :204:34, :205:34, :206:34, :207:34, :208:34, :209:34, :235:10, :307:19, :308:11, :309:11, :310:11, :311:11, :312:11, :313:11, :314:11, :315:11, :316:11, :317:11, :318:11, :319:11, :320:11, :321:11, :322:11, :323:11, :324:11, :325:11, :326:11, :327:11, :328:11, :329:11, :330:11, :331:11, :332:11, :333:11, :334:12, :335:12, :336:12, :337:12, :338:12, :339:12, :340:12, :341:12, :342:12, :343:12, :344:12, :345:12, :346:12, :347:12, :348:12, :349:12, :350:12, :351:12, :352:12, :353:12, :354:12, :355:12, :356:12, :357:12, :358:12, :359:12, :360:12, :361:12, :362:12, :363:12, :364:12, :365:12, :366:12, :367:12, :368:12, :369:12, :370:12, :371:12, :372:12, :373:12, :374:12, :375:12, :376:12, :377:12, :378:12, :546:11
            state_reg224 <= 3'h4;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:224:15, :547:13
          else begin	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:546:11
            state_reg224 <= 3'h5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:225:15, :549:13
            phi_reg374 <= phi_reg226;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:233:10, :550:13
          end
        end
        3'b100: begin
          state_reg224 <= 3'h5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:225:15, :554:11
          phi_reg374 <= phi_reg226 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:89:18, :233:10, :379:12, :555:11
        end
        3'b101: begin
          state_reg224 <= 3'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:221:14, :558:11
          phi_reg226 <= phi_reg374;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:381:12, :559:11
          phi_reg228 <= phi_reg228 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:184:19, :235:10, :522:12, :560:11
        end
        3'b110:
          state_reg224 <= state_reg224;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:231:10, :563:11
        default:
          state_reg224 <= state_reg224;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:231:10, :566:11
      endcase	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3740555853/design.pipeline.mlir:231:10, :528:9
    end
  end // always @(posedge)
endmodule


// mygo autogenerated loop FSM fallback modules
module main__proc_main__loop0_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t2_83
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule
