// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:2:36
);

  reg  [63:0] test_in_0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:4:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:5:5
    test_in_0 = 64'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:3:15, :6:7
  reg  [63:0] test_in_1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:9:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:10:5
    test_in_1 = 64'h3FC65717FCED55C1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:8:33, :11:7
  reg  [63:0] test_in_10;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:14:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:15:5
    test_in_10 = 64'h3FFBECDDFC28AB31;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:13:33, :16:7
  reg  [63:0] test_in_11;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:19:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:20:5
    test_in_11 = 64'h3FFEB7C0FBC655E9;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:18:33, :21:7
  reg  [63:0] test_in_12;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:24:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:25:5
    test_in_12 = 64'h4000C151FDB20051;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:23:33, :26:7
  reg  [63:0] test_in_13;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:29:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:30:5
    test_in_13 = 64'h400226C37D80D5AD;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:28:33, :31:7
  reg  [63:0] test_in_14;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:34:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:35:5
    test_in_14 = 64'h40038C34FD4FAB09;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:33:33, :36:7
  reg  [63:0] test_in_15;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:39:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:40:5
    test_in_15 = 64'h4004F1A67D1E8065;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:38:33, :41:7
  reg  [63:0] test_in_16;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:44:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:45:5
    test_in_16 = 64'h40065717FCED55C1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:43:33, :46:7
  reg  [63:0] test_in_17;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:49:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:50:5
    test_in_17 = 64'h4007BC897CBC2B1D;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:48:33, :51:7
  reg  [63:0] test_in_18;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:54:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:55:5
    test_in_18 = 64'h400921FAFC8B0079;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:53:33, :56:7
  reg  [63:0] test_in_19;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:59:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:60:5
    test_in_19 = 64'h400A876C7C59D5D5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:58:33, :61:7
  reg  [63:0] test_in_2;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:64:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:65:5
    test_in_2 = 64'h3FD65717FCED55C1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:63:33, :66:7
  reg  [63:0] test_in_20;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:69:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:70:5
    test_in_20 = 64'h400BECDDFC28AB31;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:68:33, :71:7
  reg  [63:0] test_in_21;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:74:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:75:5
    test_in_21 = 64'h400D524F7BF7808D;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:73:33, :76:7
  reg  [63:0] test_in_22;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:79:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:80:5
    test_in_22 = 64'h400EB7C0FBC655E9;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:78:33, :81:7
  reg  [63:0] test_in_23;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:84:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:85:5
    test_in_23 = 64'h40100E993DCA95A3;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:83:33, :86:7
  reg  [63:0] test_in_24;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:89:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:90:5
    test_in_24 = 64'h4010C151FDB20051;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:88:33, :91:7
  reg  [63:0] test_in_25;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:94:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:95:5
    test_in_25 = 64'h4011740ABD996AFF;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:93:33, :96:7
  reg  [63:0] test_in_26;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:99:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:100:5
    test_in_26 = 64'h401226C37D80D5AD;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:98:33, :101:7
  reg  [63:0] test_in_27;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:104:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:105:5
    test_in_27 = 64'h4012D97C3D68405B;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:103:33, :106:7
  reg  [63:0] test_in_28;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:109:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:110:5
    test_in_28 = 64'h40138C34FD4FAB09;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:108:33, :111:7
  reg  [63:0] test_in_29;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:114:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:115:5
    test_in_29 = 64'h40143EEDBD3715B7;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:113:33, :116:7
  reg  [63:0] test_in_3;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:119:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:120:5
    test_in_3 = 64'h3FE0C151FDB20051;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:118:33, :121:7
  reg  [63:0] test_in_30;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:124:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:125:5
    test_in_30 = 64'h4014F1A67D1E8065;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:123:33, :126:7
  reg  [63:0] test_in_31;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:129:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:130:5
    test_in_31 = 64'h4015A45F3D05EB13;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:128:33, :131:7
  reg  [63:0] test_in_32;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:134:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:135:5
    test_in_32 = 64'h40165717FCED55C1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:133:33, :136:7
  reg  [63:0] test_in_33;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:139:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:140:5
    test_in_33 = 64'h401709D0BCD4C06F;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:138:33, :141:7
  reg  [63:0] test_in_34;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:144:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:145:5
    test_in_34 = 64'h4017BC897CBC2B1D;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:143:33, :146:7
  reg  [63:0] test_in_35;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:149:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:150:5
    test_in_35 = 64'h40186F423CA395CB;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:148:33, :151:7
  reg  [63:0] test_in_4;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:154:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:155:5
    test_in_4 = 64'h3FE65717FCED55C1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:153:33, :156:7
  reg  [63:0] test_in_5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:159:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:160:5
    test_in_5 = 64'h3FEBECDDFC28AB31;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:158:33, :161:7
  reg  [63:0] test_in_6;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:164:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:165:5
    test_in_6 = 64'h3FF0C151FDB20051;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:163:33, :166:7
  reg  [63:0] test_in_7;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:169:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:170:5
    test_in_7 = 64'h3FF38C34FD4FAB09;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:168:33, :171:7
  reg  [63:0] test_in_8;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:174:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:175:5
    test_in_8 = 64'h3FF65717FCED55C1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:173:33, :176:7
  reg  [63:0] test_in_9;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:179:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:180:5
    test_in_9 = 64'h3FF921FAFC8B0079;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:178:33, :181:7
  reg  [63:0] test_out_0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:184:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:185:5
    test_out_0 = 64'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:183:17, :186:7
  reg  [63:0] test_out_1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:189:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:190:5
    test_out_1 = 64'h3FC63A1A335AADCD;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:188:33, :191:7
  reg  [63:0] test_out_10;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:194:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:195:5
    test_out_10 = 64'h3FEF838BB0147989;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:193:33, :196:7
  reg  [63:0] test_out_11;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:199:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:200:5
    test_out_11 = 64'h3FEE11F692D962B4;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:198:33, :201:7
  reg  [63:0] test_out_12;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:204:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:205:5
    test_out_12 = 64'h3FEBB67B77C0142D;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:203:33, :206:7
  reg  [63:0] test_out_13;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:209:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:210:5
    test_out_13 = 64'h3FE883709D4EA869;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:208:33, :211:7
  reg  [63:0] test_out_14;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:214:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:215:5
    test_out_14 = 64'h3FE491B81D72D8E8;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:213:33, :216:7
  reg  [63:0] test_out_15;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:219:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:220:5
    test_out_15 = 64'h3FE00000EA5F43C8;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:218:33, :221:7
  reg  [63:0] test_out_16;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:224:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:225:5
    test_out_16 = 64'h3FD5E3AA4E0590C5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:223:33, :226:7
  reg  [63:0] test_out_17;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:229:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:230:5
    test_out_17 = 64'h3FC63A1D2189552C;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:228:33, :231:7
  reg  [63:0] test_out_18;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:234:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:235:5
    test_out_18 = 64'h3EA6AEDFFC454B91;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:233:33, :236:7
  reg  [63:0] test_out_19;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:239:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:240:5
    test_out_19 = 64'hBFC63A1444DDB37C;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:238:34, :241:7
  reg  [63:0] test_out_2;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:244:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:245:5
    test_out_2 = 64'h3FD5E3A82B09BF3E;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:243:33, :246:7
  reg  [63:0] test_out_20;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:249:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:250:5
    test_out_20 = 64'hBFD5E3A4E68F8F3E;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:248:34, :251:7
  reg  [63:0] test_out_21;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:254:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:255:5
    test_out_21 = 64'hBFDFFFFD494CF96B;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:253:34, :256:7
  reg  [63:0] test_out_22;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:259:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:260:5
    test_out_22 = 64'hBFE491B61CB9A3D3;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:258:34, :261:7
  reg  [63:0] test_out_23;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:264:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:265:5
    test_out_23 = 64'hBFE8836EB2DCF815;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:263:34, :266:7
  reg  [63:0] test_out_24;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:269:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:270:5
    test_out_24 = 64'hBFEBB67A740AAE32;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:268:34, :271:7
  reg  [63:0] test_out_25;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:274:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:275:5
    test_out_25 = 64'hBFEE11F5912D2157;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:273:34, :276:7
  reg  [63:0] test_out_26;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:279:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:280:5
    test_out_26 = 64'hBFEF838B1AC64AFC;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:278:34, :281:7
  reg  [63:0] test_out_27;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:284:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:285:5
    test_out_27 = 64'hBFEFFFFFC2E5DC8F;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:283:34, :286:7
  reg  [63:0] test_out_28;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:289:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:290:5
    test_out_28 = 64'hBFEF838B5EA2E7EA;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:288:34, :291:7
  reg  [63:0] test_out_29;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:294:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:295:5
    test_out_29 = 64'hBFEE11F7112DAE27;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:293:34, :296:7
  reg  [63:0] test_out_3;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:299:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:300:5
    test_out_3 = 64'h3FDFFFFF91F9AA91;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:298:33, :301:7
  reg  [63:0] test_out_30;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:304:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:305:5
    test_out_30 = 64'hBFEBB67C2C31CB4A;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:303:34, :306:7
  reg  [63:0] test_out_31;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:309:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:310:5
    test_out_31 = 64'hBFE883716E6FD781;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:308:34, :311:7
  reg  [63:0] test_out_32;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:314:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:315:5
    test_out_32 = 64'hBFE491B9CD1B5D56;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:313:34, :316:7
  reg  [63:0] test_out_33;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:319:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:320:5
    test_out_33 = 64'hBFE000021D0CA30D;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:318:34, :321:7
  reg  [63:0] test_out_34;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:324:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:325:5
    test_out_34 = 64'hBFD5E3AD0A69CAF7;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:323:34, :326:7
  reg  [63:0] test_out_35;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:329:20
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:330:5
    test_out_35 = 64'hBFC63A23C48863DD;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:328:34, :331:7
  reg  [63:0] test_out_4;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:334:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:335:5
    test_out_4 = 64'h3FE491B716C242E3;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:333:33, :336:7
  reg  [63:0] test_out_5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:339:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:340:5
    test_out_5 = 64'h3FE8836F672614A6;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:338:33, :341:7
  reg  [63:0] test_out_6;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:344:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:345:5
    test_out_6 = 64'h3FEBB67AC40B2BED;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:343:33, :346:7
  reg  [63:0] test_out_7;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:349:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:350:5
    test_out_7 = 64'h3FEE11F6127E28AD;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:348:33, :351:7
  reg  [63:0] test_out_8;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:354:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:355:5
    test_out_8 = 64'h3FEF838B6ADFFAC0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:353:33, :356:7
  reg  [63:0] test_out_9;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:359:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:360:5
    test_out_9 = 64'h3FEFFFFFE1CBD7AA;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:358:33, :361:7
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:364:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:365:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:363:15, :366:7
  reg  [3:0]  state_reg164;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:532:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:533:5
    state_reg164 = 4'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:521:14, :534:7
  reg signed [31:0] print_reg166;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:537:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:539:5
    print_reg166 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:538:19, :540:7
  reg  [63:0] print_reg168;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:542:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:544:5
    print_reg168 = 64'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:543:19, :545:7
  reg  [63:0] print_reg170;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:547:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:549:5
    print_reg170 = 64'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:548:19, :550:7
  reg  [63:0] print_reg172;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:552:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:554:5
    print_reg172 = 64'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:553:19, :555:7
  reg  [63:0] print_reg174;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:557:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:559:5
    print_reg174 = 64'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:558:19, :560:7
  reg  [31:0] phi_reg176;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:562:19
  reg  [31:0] phi_reg178;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:564:19
  wire [63:0] _GEN =
    phi_reg178 == 32'h23
      ? test_in_35
      : phi_reg178 == 32'h22
          ? test_in_34
          : phi_reg178 == 32'h21
              ? test_in_33
              : phi_reg178 == 32'h20
                  ? test_in_32
                  : phi_reg178 == 32'h1F
                      ? test_in_31
                      : phi_reg178 == 32'h1E
                          ? test_in_30
                          : phi_reg178 == 32'h1D
                              ? test_in_29
                              : phi_reg178 == 32'h1C
                                  ? test_in_28
                                  : phi_reg178 == 32'h1B
                                      ? test_in_27
                                      : phi_reg178 == 32'h1A
                                          ? test_in_26
                                          : phi_reg178 == 32'h19
                                              ? test_in_25
                                              : phi_reg178 == 32'h18
                                                  ? test_in_24
                                                  : phi_reg178 == 32'h17
                                                      ? test_in_23
                                                      : phi_reg178 == 32'h16
                                                          ? test_in_22
                                                          : phi_reg178 == 32'h15
                                                              ? test_in_21
                                                              : phi_reg178 == 32'h14
                                                                  ? test_in_20
                                                                  : phi_reg178 == 32'h13
                                                                      ? test_in_19
                                                                      : phi_reg178 == 32'h12
                                                                          ? test_in_18
                                                                          : phi_reg178 == 32'h11
                                                                              ? test_in_17
                                                                              : phi_reg178 == 32'h10
                                                                                  ? test_in_16
                                                                                  : phi_reg178 == 32'hF
                                                                                      ? test_in_15
                                                                                      : phi_reg178 == 32'hE
                                                                                          ? test_in_14
                                                                                          : phi_reg178 == 32'hD
                                                                                              ? test_in_13
                                                                                              : phi_reg178 == 32'hC
                                                                                                  ? test_in_12
                                                                                                  : phi_reg178 == 32'hB
                                                                                                      ? test_in_11
                                                                                                      : phi_reg178 == 32'hA
                                                                                                          ? test_in_10
                                                                                                          : phi_reg178 == 32'h9
                                                                                                              ? test_in_9
                                                                                                              : phi_reg178 == 32'h8
                                                                                                                  ? test_in_8
                                                                                                                  : phi_reg178 == 32'h7
                                                                                                                      ? test_in_7
                                                                                                                      : phi_reg178 == 32'h6
                                                                                                                          ? test_in_6
                                                                                                                          : phi_reg178 == 32'h5
                                                                                                                              ? test_in_5
                                                                                                                              : phi_reg178 == 32'h4
                                                                                                                                  ? test_in_4
                                                                                                                                  : phi_reg178 == 32'h3
                                                                                                                                      ? test_in_3
                                                                                                                                      : phi_reg178 == 32'h2
                                                                                                                                          ? test_in_2
                                                                                                                                          : phi_reg178 == 32'h1
                                                                                                                                              ? test_in_1
                                                                                                                                              : test_in_0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:368:15, :369:15, :370:15, :371:15, :372:16, :373:16, :374:16, :375:16, :376:16, :377:16, :378:16, :379:16, :380:16, :381:16, :382:16, :383:16, :384:16, :385:16, :386:16, :387:16, :388:16, :389:16, :390:16, :391:16, :392:16, :393:16, :394:16, :395:16, :396:16, :397:16, :516:19, :517:19, :518:19, :519:19, :520:19, :565:10, :567:10, :568:10, :569:10, :570:10, :571:10, :572:10, :573:11, :574:11, :575:11, :576:11, :577:11, :578:11, :579:11, :580:11, :581:11, :582:11, :583:11, :584:11, :585:11, :586:11, :587:11, :588:11, :589:11, :590:11, :591:11, :592:11, :593:11, :594:11, :595:11, :596:11, :597:11, :598:11, :599:11, :600:11, :601:11, :602:11, :603:11, :604:11, :605:11, :606:11, :607:11, :608:11, :609:11, :610:11, :611:11, :612:11, :613:11, :614:11, :615:11, :616:11, :617:11, :618:11, :619:11, :620:11, :621:11, :622:11, :623:11, :624:11, :625:11, :626:11, :627:11, :628:11, :629:11, :630:11, :631:11, :632:11, :633:11, :634:11, :635:11, :636:11, :637:11, :638:11, :639:11, :640:11, :641:11, :642:11, :643:11, :644:11, :645:11, :646:11, :647:11, :648:11, :649:11, :650:11, :651:11, :652:11, :653:11, :654:11, :655:11, :656:11, :657:11, :658:11, :659:11, :660:11, :661:11, :662:11, :663:12, :664:12, :665:12, :666:12, :667:12, :668:12, :669:12, :670:12, :671:12, :672:12
  reg  [63:0] phi_reg289;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:675:19
  reg  [63:0] phi_reg291;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:677:19
  reg  [31:0] phi_reg293;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:679:19
  wire [31:0] _GEN_0 = phi_reg293 * 32'h2 * (phi_reg293 * 32'h2 + 32'h1);	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:401:15, :402:17, :403:17, :680:12, :682:12, :683:12, :684:12, :685:12
  wire [63:0] _GEN_1 = phi_reg291 * (64'h0 - _GEN) * _GEN / {{32{_GEN_0[31]}}, _GEN_0};	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:398:17, :672:12, :673:12, :674:12, :678:12, :681:12, :685:12, :686:12, :687:12, :688:12, :689:12
  wire [63:0] _GEN_2 = phi_reg289 + _GEN_1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:676:12, :689:12, :690:12
  reg  [31:0] phi_reg420;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:806:19
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1022:5
    if (rst)	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1023:7
      state_reg164 <= 4'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:521:14, :1024:9
    else begin	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1023:7
      case (state_reg164)	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:536:10, :1026:9
        4'b0000: begin
          state_reg164 <= 4'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:522:14, :1028:11
          phi_reg176 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:513:19, :1029:11
          phi_reg178 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:514:19, :1030:11
        end
        4'b0001: begin
          if ($signed(phi_reg178) < 32'sh24)	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:515:16, :565:10, :566:10, :1033:11
            state_reg164 <= 4'h3;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:524:14, :1034:13
          else	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1033:11
            state_reg164 <= 4'h2;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:523:14, :1036:13
        end
        4'b0010: begin
          print_reg166 = phi_reg176;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:563:10, :1040:11
          $write("%0d\n", print_reg166);	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1021:25, :1041:18, :1042:11
          state_reg164 <= 4'hA;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:531:15, :1043:11
        end
        4'b0011:
          state_reg164 <= 4'h4;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:525:14, :1046:11
        4'b0100: begin
          state_reg164 <= 4'h5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:526:14, :1049:11
          phi_reg289 <= _GEN;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:672:12, :1050:11
          phi_reg291 <= _GEN;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:672:12, :1051:11
          phi_reg293 <= 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:400:15, :1052:11
        end
        4'b0101: begin
          if ($signed(_GEN_1 & ~(64'h8000000000000000)) < 64'sh3EE4F8B588E368F1)	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:399:33, :405:34, :689:12, :694:12, :695:12, :696:12, :1055:11
            state_reg164 <= 4'h6;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:527:14, :1056:13
          else begin	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1055:11
            state_reg164 <= 4'h5;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:526:14, :1058:13
            phi_reg289 <= _GEN_2;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:690:12, :1059:13
            phi_reg291 <= _GEN_1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:689:12, :1060:13
            phi_reg293 <= phi_reg293 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:404:17, :680:12, :691:12, :1061:13
          end
        end
        4'b0110:
          state_reg164 <= 4'h7;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:528:14, :1065:11
        4'b0111: begin
          if (_GEN_2 != (phi_reg178 == 32'h23
                           ? test_out_35
                           : phi_reg178 == 32'h22
                               ? test_out_34
                               : phi_reg178 == 32'h21
                                   ? test_out_33
                                   : phi_reg178 == 32'h20
                                       ? test_out_32
                                       : phi_reg178 == 32'h1F
                                           ? test_out_31
                                           : phi_reg178 == 32'h1E
                                               ? test_out_30
                                               : phi_reg178 == 32'h1D
                                                   ? test_out_29
                                                   : phi_reg178 == 32'h1C
                                                       ? test_out_28
                                                       : phi_reg178 == 32'h1B
                                                           ? test_out_27
                                                           : phi_reg178 == 32'h1A
                                                               ? test_out_26
                                                               : phi_reg178 == 32'h19
                                                                   ? test_out_25
                                                                   : phi_reg178 == 32'h18
                                                                       ? test_out_24
                                                                       : phi_reg178 == 32'h17
                                                                           ? test_out_23
                                                                           : phi_reg178 == 32'h16
                                                                               ? test_out_22
                                                                               : phi_reg178 == 32'h15
                                                                                   ? test_out_21
                                                                                   : phi_reg178 == 32'h14
                                                                                       ? test_out_20
                                                                                       : phi_reg178 == 32'h13
                                                                                           ? test_out_19
                                                                                           : phi_reg178 == 32'h12
                                                                                               ? test_out_18
                                                                                               : phi_reg178 == 32'h11
                                                                                                   ? test_out_17
                                                                                                   : phi_reg178 == 32'h10
                                                                                                       ? test_out_16
                                                                                                       : phi_reg178 == 32'hF
                                                                                                           ? test_out_15
                                                                                                           : phi_reg178 == 32'hE
                                                                                                               ? test_out_14
                                                                                                               : phi_reg178 == 32'hD
                                                                                                                   ? test_out_13
                                                                                                                   : phi_reg178 == 32'hC
                                                                                                                       ? test_out_12
                                                                                                                       : phi_reg178 == 32'hB
                                                                                                                           ? test_out_11
                                                                                                                           : phi_reg178 == 32'hA
                                                                                                                               ? test_out_10
                                                                                                                               : phi_reg178 == 32'h9
                                                                                                                                   ? test_out_9
                                                                                                                                   : phi_reg178 == 32'h8
                                                                                                                                       ? test_out_8
                                                                                                                                       : phi_reg178 == 32'h7
                                                                                                                                           ? test_out_7
                                                                                                                                           : phi_reg178 == 32'h6
                                                                                                                                               ? test_out_6
                                                                                                                                               : phi_reg178 == 32'h5
                                                                                                                                                   ? test_out_5
                                                                                                                                                   : phi_reg178 == 32'h4
                                                                                                                                                       ? test_out_4
                                                                                                                                                       : phi_reg178 == 32'h3
                                                                                                                                                           ? test_out_3
                                                                                                                                                           : phi_reg178 == 32'h2
                                                                                                                                                               ? test_out_2
                                                                                                                                                               : phi_reg178 == 32'h1
                                                                                                                                                                   ? test_out_1
                                                                                                                                                                   : test_out_0))	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:406:17, :407:17, :408:15, :409:15, :410:15, :411:17, :412:17, :413:17, :414:18, :415:19, :416:19, :417:19, :418:19, :419:19, :420:19, :421:19, :422:19, :423:19, :424:19, :425:19, :426:19, :427:19, :428:19, :429:19, :430:19, :431:19, :432:19, :433:19, :434:19, :435:19, :436:19, :437:19, :438:19, :439:19, :440:19, :565:10, :690:12, :698:12, :699:12, :700:12, :701:12, :702:12, :703:12, :704:12, :705:12, :706:12, :707:12, :708:12, :709:12, :710:12, :711:12, :712:12, :713:12, :714:12, :715:12, :716:12, :717:12, :718:12, :719:12, :720:12, :721:12, :722:12, :723:12, :724:12, :725:12, :726:12, :727:12, :728:12, :729:12, :730:12, :731:12, :732:12, :733:12, :734:12, :735:12, :736:12, :737:12, :738:12, :739:12, :740:12, :741:12, :742:12, :743:12, :744:12, :745:12, :746:12, :747:12, :748:12, :749:12, :750:12, :751:12, :752:12, :753:12, :754:12, :755:12, :756:12, :757:12, :758:12, :759:12, :760:12, :761:12, :762:12, :763:12, :764:12, :765:12, :766:12, :767:12, :768:12, :769:12, :770:12, :771:12, :772:12, :773:12, :774:12, :775:12, :776:12, :777:12, :778:12, :779:12, :780:12, :781:12, :782:12, :783:12, :784:12, :785:12, :786:12, :787:12, :788:12, :789:12, :790:12, :791:12, :792:12, :793:12, :794:12, :795:12, :796:12, :797:12, :798:12, :799:12, :800:12, :801:12, :802:12, :803:12, :804:12, :1068:11
            state_reg164 <= 4'h8;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:529:15, :1069:13
          else begin	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1068:11
            state_reg164 <= 4'h9;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:530:15, :1071:13
            phi_reg420 <= phi_reg176;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:563:10, :1072:13
          end
        end
        4'b1000: begin
          state_reg164 <= 4'h9;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:530:15, :1076:11
          phi_reg420 <= phi_reg176 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:441:18, :563:10, :805:12, :1077:11
        end
        4'b1001: begin
          print_reg168 =
            phi_reg178 == 32'h23
              ? test_in_35
              : phi_reg178 == 32'h22
                  ? test_in_34
                  : phi_reg178 == 32'h21
                      ? test_in_33
                      : phi_reg178 == 32'h20
                          ? test_in_32
                          : phi_reg178 == 32'h1F
                              ? test_in_31
                              : phi_reg178 == 32'h1E
                                  ? test_in_30
                                  : phi_reg178 == 32'h1D
                                      ? test_in_29
                                      : phi_reg178 == 32'h1C
                                          ? test_in_28
                                          : phi_reg178 == 32'h1B
                                              ? test_in_27
                                              : phi_reg178 == 32'h1A
                                                  ? test_in_26
                                                  : phi_reg178 == 32'h19
                                                      ? test_in_25
                                                      : phi_reg178 == 32'h18
                                                          ? test_in_24
                                                          : phi_reg178 == 32'h17
                                                              ? test_in_23
                                                              : phi_reg178 == 32'h16
                                                                  ? test_in_22
                                                                  : phi_reg178 == 32'h15
                                                                      ? test_in_21
                                                                      : phi_reg178 == 32'h14
                                                                          ? test_in_20
                                                                          : phi_reg178 == 32'h13
                                                                              ? test_in_19
                                                                              : phi_reg178 == 32'h12
                                                                                  ? test_in_18
                                                                                  : phi_reg178 == 32'h11
                                                                                      ? test_in_17
                                                                                      : phi_reg178 == 32'h10
                                                                                          ? test_in_16
                                                                                          : phi_reg178 == 32'hF
                                                                                              ? test_in_15
                                                                                              : phi_reg178 == 32'hE
                                                                                                  ? test_in_14
                                                                                                  : phi_reg178 == 32'hD
                                                                                                      ? test_in_13
                                                                                                      : phi_reg178 == 32'hC
                                                                                                          ? test_in_12
                                                                                                          : phi_reg178 == 32'hB
                                                                                                              ? test_in_11
                                                                                                              : phi_reg178 == 32'hA
                                                                                                                  ? test_in_10
                                                                                                                  : phi_reg178 == 32'h9
                                                                                                                      ? test_in_9
                                                                                                                      : phi_reg178 == 32'h8
                                                                                                                          ? test_in_8
                                                                                                                          : phi_reg178 == 32'h7
                                                                                                                              ? test_in_7
                                                                                                                              : phi_reg178 == 32'h6
                                                                                                                                  ? test_in_6
                                                                                                                                  : phi_reg178 == 32'h5
                                                                                                                                      ? test_in_5
                                                                                                                                      : phi_reg178 == 32'h4
                                                                                                                                          ? test_in_4
                                                                                                                                          : phi_reg178 == 32'h3
                                                                                                                                              ? test_in_3
                                                                                                                                              : phi_reg178 == 32'h2
                                                                                                                                                  ? test_in_2
                                                                                                                                                  : phi_reg178 == 32'h1
                                                                                                                                                      ? test_in_1
                                                                                                                                                      : test_in_0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:442:18, :443:18, :444:18, :445:18, :446:18, :447:18, :448:18, :449:18, :450:18, :451:19, :452:19, :453:19, :454:19, :455:19, :456:19, :457:19, :458:19, :459:19, :460:19, :461:19, :462:19, :463:19, :464:19, :465:19, :466:19, :467:19, :468:19, :469:19, :470:19, :471:19, :472:19, :473:19, :474:19, :475:19, :476:19, :565:10, :808:12, :809:12, :810:12, :811:12, :812:12, :813:12, :814:12, :815:12, :816:12, :817:12, :818:12, :819:12, :820:12, :821:12, :822:12, :823:12, :824:12, :825:12, :826:12, :827:12, :828:12, :829:12, :830:12, :831:12, :832:12, :833:12, :834:12, :835:12, :836:12, :837:12, :838:12, :839:12, :840:12, :841:12, :842:12, :843:12, :844:12, :845:12, :846:12, :847:12, :848:12, :849:12, :850:12, :851:12, :852:12, :853:12, :854:12, :855:12, :856:12, :857:12, :858:12, :859:12, :860:12, :861:12, :862:12, :863:12, :864:12, :865:12, :866:12, :867:12, :868:12, :869:12, :870:12, :871:12, :872:12, :873:12, :874:12, :875:12, :876:12, :877:12, :878:12, :879:12, :880:12, :881:12, :882:12, :883:12, :884:12, :885:12, :886:12, :887:12, :888:12, :889:12, :890:12, :891:12, :892:12, :893:12, :894:12, :895:12, :896:12, :897:12, :898:12, :899:12, :900:12, :901:12, :902:12, :903:12, :904:12, :905:12, :906:12, :907:12, :908:12, :909:12, :910:12, :911:12, :912:12, :913:12, :1080:11
          print_reg170 =
            phi_reg178 == 32'h23
              ? test_out_35
              : phi_reg178 == 32'h22
                  ? test_out_34
                  : phi_reg178 == 32'h21
                      ? test_out_33
                      : phi_reg178 == 32'h20
                          ? test_out_32
                          : phi_reg178 == 32'h1F
                              ? test_out_31
                              : phi_reg178 == 32'h1E
                                  ? test_out_30
                                  : phi_reg178 == 32'h1D
                                      ? test_out_29
                                      : phi_reg178 == 32'h1C
                                          ? test_out_28
                                          : phi_reg178 == 32'h1B
                                              ? test_out_27
                                              : phi_reg178 == 32'h1A
                                                  ? test_out_26
                                                  : phi_reg178 == 32'h19
                                                      ? test_out_25
                                                      : phi_reg178 == 32'h18
                                                          ? test_out_24
                                                          : phi_reg178 == 32'h17
                                                              ? test_out_23
                                                              : phi_reg178 == 32'h16
                                                                  ? test_out_22
                                                                  : phi_reg178 == 32'h15
                                                                      ? test_out_21
                                                                      : phi_reg178 == 32'h14
                                                                          ? test_out_20
                                                                          : phi_reg178 == 32'h13
                                                                              ? test_out_19
                                                                              : phi_reg178 == 32'h12
                                                                                  ? test_out_18
                                                                                  : phi_reg178 == 32'h11
                                                                                      ? test_out_17
                                                                                      : phi_reg178 == 32'h10
                                                                                          ? test_out_16
                                                                                          : phi_reg178 == 32'hF
                                                                                              ? test_out_15
                                                                                              : phi_reg178 == 32'hE
                                                                                                  ? test_out_14
                                                                                                  : phi_reg178 == 32'hD
                                                                                                      ? test_out_13
                                                                                                      : phi_reg178 == 32'hC
                                                                                                          ? test_out_12
                                                                                                          : phi_reg178 == 32'hB
                                                                                                              ? test_out_11
                                                                                                              : phi_reg178 == 32'hA
                                                                                                                  ? test_out_10
                                                                                                                  : phi_reg178 == 32'h9
                                                                                                                      ? test_out_9
                                                                                                                      : phi_reg178 == 32'h8
                                                                                                                          ? test_out_8
                                                                                                                          : phi_reg178 == 32'h7
                                                                                                                              ? test_out_7
                                                                                                                              : phi_reg178 == 32'h6
                                                                                                                                  ? test_out_6
                                                                                                                                  : phi_reg178 == 32'h5
                                                                                                                                      ? test_out_5
                                                                                                                                      : phi_reg178 == 32'h4
                                                                                                                                          ? test_out_4
                                                                                                                                          : phi_reg178 == 32'h3
                                                                                                                                              ? test_out_3
                                                                                                                                              : phi_reg178 == 32'h2
                                                                                                                                                  ? test_out_2
                                                                                                                                                  : phi_reg178 == 32'h1
                                                                                                                                                      ? test_out_1
                                                                                                                                                      : test_out_0;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:477:18, :478:18, :479:18, :480:18, :481:18, :482:18, :483:18, :484:18, :485:18, :486:19, :487:19, :488:19, :489:19, :490:19, :491:19, :492:19, :493:19, :494:19, :495:19, :496:19, :497:19, :498:19, :499:19, :500:19, :501:19, :502:19, :503:19, :504:20, :505:20, :506:20, :507:20, :508:20, :509:20, :510:20, :511:20, :565:10, :914:12, :915:12, :916:12, :917:12, :918:12, :919:12, :920:12, :921:12, :922:12, :923:12, :924:12, :925:12, :926:12, :927:12, :928:12, :929:12, :930:12, :931:12, :932:12, :933:12, :934:12, :935:12, :936:12, :937:12, :938:12, :939:12, :940:12, :941:12, :942:12, :943:12, :944:12, :945:12, :946:12, :947:12, :948:12, :949:12, :950:12, :951:12, :952:12, :953:12, :954:12, :955:12, :956:12, :957:12, :958:12, :959:12, :960:12, :961:12, :962:12, :963:12, :964:12, :965:12, :966:12, :967:12, :968:12, :969:12, :970:12, :971:12, :972:12, :973:12, :974:12, :975:12, :976:12, :977:12, :978:12, :979:12, :980:12, :981:12, :982:12, :983:12, :984:12, :985:12, :986:12, :987:12, :988:12, :989:12, :990:12, :991:12, :992:12, :993:12, :994:12, :995:12, :996:12, :997:12, :998:12, :999:12, :1000:12, :1001:12, :1002:12, :1003:12, :1004:12, :1005:12, :1006:12, :1007:12, :1008:12, :1009:12, :1010:12, :1011:12, :1012:12, :1013:12, :1014:12, :1015:12, :1016:12, :1017:12, :1018:12, :1019:12, :1082:11
          print_reg172 = _GEN_2;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:690:12, :1084:11
          print_reg174 = _GEN_2;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:690:12, :1086:11
          $write("input=%016x expected=%016x output=%016x (%f)\n",
                  print_reg168, print_reg170, print_reg172, $bitstoreal(print_reg174));	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:1021:25, :1081:18, :1083:18, :1085:18, :1087:18, :1088:11
          state_reg164 <= 4'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:522:14, :1089:11
          phi_reg176 <= phi_reg420;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:807:12, :1090:11
          phi_reg178 <= phi_reg178 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:512:19, :565:10, :1020:12, :1091:11
        end
        4'b1010:
          state_reg164 <= state_reg164;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:536:10, :1094:11
        default:
          state_reg164 <= state_reg164;	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:536:10, :1097:11
      endcase	// /home/qinkejiu/mygo/tests/CHStone/dfsin/.mygo-tmp/.mygo-circt-3560661211/design.pipeline.mlir:536:10, :1026:9
    end
  end // always @(posedge)
endmodule


// mygo autogenerated loop FSM fallback modules
module main__proc_main__loop0_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t2_83
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule
