// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:2:36
);

  reg signed [31:0] in_i_0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:4:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:5:5
    in_i_0 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:3:15, :6:7
  reg signed [31:0] in_i_1;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:9:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:10:5
    in_i_1 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:8:17, :11:7
  reg [31:0] outData_0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:14:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:15:5
    outData_0 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:13:17, :16:7
  reg [31:0] outData_1;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:19:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:20:5
    outData_1 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:18:17, :21:7
  reg [31:0] outData_2;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:24:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:25:5
    outData_2 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:23:17, :26:7
  reg [31:0] outData_3;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:29:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:30:5
    outData_3 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:28:17, :31:7
  reg [31:0] outData_4;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:34:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:35:5
    outData_4 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:33:17, :36:7
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:39:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:40:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:38:17, :41:7
  reg        state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:46:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:47:5
    state_reg3 = 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:44:14, :48:7
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:52:5
    if (rst)	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:53:7
      state_reg3 <= 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:44:14, :54:9
    else begin	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:53:7
      case (state_reg3)	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:50:10, :56:9
        1'b0: begin
          $write("%0d\n", 32'sh0);	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:43:17, :51:25, :58:11
          state_reg3 <= 1'h1;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:45:13, :59:11
        end
        1'b1:
          state_reg3 <= state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:50:10, :62:11
        default:
          state_reg3 <= state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:50:10, :65:11
      endcase	// /home/qinkejiu/mygo/tests/CHStone/sha/.mygo-tmp/.mygo-circt-4057877302/design.pipeline.mlir:50:10, :56:9
    end
  end // always @(posedge)
endmodule

