// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:2:36
);

  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:4:16
  initial	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:5:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:3:15, :6:7
  reg         state_reg5;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:13:19
  initial	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:14:5
    state_reg5 = 1'h0;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:11:14, :15:7
  reg signed [15:0] print_reg7;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:18:19
  initial	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:20:5
    print_reg7 = 16'h0;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:19:15, :21:7
  reg  [31:0] print_reg9;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:23:19
  initial	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:25:5
    print_reg9 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:24:17, :26:7
  wire [15:0] _GEN = {8'h0, 8'h5} - 16'hC;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:8:14, :28:14, :29:10, :30:10
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:36:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:37:7
      state_reg5 <= 1'h0;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:11:14, :38:9
    else begin	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:37:7
      case (state_reg5)	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:17:10, :40:9
        1'b0: begin
          print_reg7 = _GEN;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:30:10, :42:11
          print_reg9 = {{16{_GEN[15]}}, _GEN} + 32'h400;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:10:18, :30:10, :31:10, :32:10, :33:10, :34:10, :44:11
          $write("acc=%0d wide=%0d\n", print_reg7, print_reg9);	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:35:25, :43:16, :45:16, :46:11
          state_reg5 <= 1'h1;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:12:13, :47:11
        end
        1'b1:
          state_reg5 <= state_reg5;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:17:10, :50:11
        default:
          state_reg5 <= state_reg5;	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:17:10, :53:11
      endcase	// /home/qinkejiu/mygo/tests/stages/type_mismatch/.mygo-tmp/.mygo-circt-3797056725/design.pipeline.mlir:17:10, :40:9
    end
  end // always @(posedge)
endmodule

