// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:2:36
);

  reg signed [31:0] A_0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:4:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:5:5
    A_0 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:3:15, :6:7
  reg signed [31:0] A_1;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:9:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:10:5
    A_1 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:8:17, :11:7
  reg signed [31:0] A_2;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:14:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:15:5
    A_2 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:13:17, :16:7
  reg signed [31:0] A_3;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:19:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:20:5
    A_3 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:18:17, :21:7
  reg signed [31:0] A_4;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:24:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:25:5
    A_4 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:23:17, :26:7
  reg signed [31:0] A_5;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:29:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:30:5
    A_5 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:28:17, :31:7
  reg signed [31:0] A_6;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:34:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:35:5
    A_6 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:33:17, :36:7
  reg signed [31:0] A_7;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:39:12
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:40:5
    A_7 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:38:17, :41:7
  reg [31:0] imem_0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:44:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:45:5
    imem_0 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:43:17, :46:7
  reg [31:0] imem_1;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:49:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:50:5
    imem_1 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:48:17, :51:7
  reg [31:0] imem_10;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:54:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:55:5
    imem_10 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:53:17, :56:7
  reg [31:0] imem_11;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:59:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:60:5
    imem_11 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:58:18, :61:7
  reg [31:0] imem_12;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:64:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:65:5
    imem_12 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:63:18, :66:7
  reg [31:0] imem_13;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:69:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:70:5
    imem_13 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:68:18, :71:7
  reg [31:0] imem_14;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:74:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:75:5
    imem_14 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:73:18, :76:7
  reg [31:0] imem_15;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:79:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:80:5
    imem_15 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:78:18, :81:7
  reg [31:0] imem_16;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:84:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:85:5
    imem_16 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:83:18, :86:7
  reg [31:0] imem_17;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:89:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:90:5
    imem_17 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:88:18, :91:7
  reg [31:0] imem_18;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:94:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:95:5
    imem_18 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:93:18, :96:7
  reg [31:0] imem_19;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:99:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:100:5
    imem_19 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:98:18, :101:7
  reg [31:0] imem_2;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:104:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:105:5
    imem_2 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:103:18, :106:7
  reg [31:0] imem_20;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:109:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:110:5
    imem_20 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:108:18, :111:7
  reg [31:0] imem_21;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:114:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:115:5
    imem_21 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:113:18, :116:7
  reg [31:0] imem_22;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:119:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:120:5
    imem_22 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:118:18, :121:7
  reg [31:0] imem_23;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:124:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:125:5
    imem_23 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:123:18, :126:7
  reg [31:0] imem_24;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:129:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:130:5
    imem_24 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:128:18, :131:7
  reg [31:0] imem_25;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:134:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:135:5
    imem_25 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:133:18, :136:7
  reg [31:0] imem_26;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:139:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:140:5
    imem_26 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:138:18, :141:7
  reg [31:0] imem_27;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:144:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:145:5
    imem_27 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:143:18, :146:7
  reg [31:0] imem_28;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:149:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:150:5
    imem_28 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:148:18, :151:7
  reg [31:0] imem_29;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:154:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:155:5
    imem_29 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:153:18, :156:7
  reg [31:0] imem_3;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:159:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:160:5
    imem_3 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:158:18, :161:7
  reg [31:0] imem_30;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:164:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:165:5
    imem_30 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:163:18, :166:7
  reg [31:0] imem_31;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:169:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:170:5
    imem_31 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:168:18, :171:7
  reg [31:0] imem_32;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:174:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:175:5
    imem_32 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:173:18, :176:7
  reg [31:0] imem_33;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:179:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:180:5
    imem_33 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:178:18, :181:7
  reg [31:0] imem_34;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:184:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:185:5
    imem_34 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:183:18, :186:7
  reg [31:0] imem_35;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:189:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:190:5
    imem_35 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:188:18, :191:7
  reg [31:0] imem_36;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:194:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:195:5
    imem_36 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:193:18, :196:7
  reg [31:0] imem_37;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:199:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:200:5
    imem_37 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:198:18, :201:7
  reg [31:0] imem_38;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:204:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:205:5
    imem_38 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:203:18, :206:7
  reg [31:0] imem_39;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:209:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:210:5
    imem_39 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:208:18, :211:7
  reg [31:0] imem_4;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:214:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:215:5
    imem_4 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:213:18, :216:7
  reg [31:0] imem_40;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:219:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:220:5
    imem_40 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:218:18, :221:7
  reg [31:0] imem_41;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:224:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:225:5
    imem_41 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:223:18, :226:7
  reg [31:0] imem_42;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:229:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:230:5
    imem_42 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:228:18, :231:7
  reg [31:0] imem_43;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:234:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:235:5
    imem_43 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:233:18, :236:7
  reg [31:0] imem_5;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:239:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:240:5
    imem_5 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:238:18, :241:7
  reg [31:0] imem_6;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:244:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:245:5
    imem_6 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:243:18, :246:7
  reg [31:0] imem_7;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:249:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:250:5
    imem_7 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:248:18, :251:7
  reg [31:0] imem_8;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:254:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:255:5
    imem_8 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:253:18, :256:7
  reg [31:0] imem_9;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:259:15
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:260:5
    imem_9 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:258:18, :261:7
  reg signed [31:0] mainResult;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:264:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:265:5
    mainResult = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:263:18, :266:7
  reg signed [31:0] outData_0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:269:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:270:5
    outData_0 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:268:18, :271:7
  reg signed [31:0] outData_1;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:274:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:275:5
    outData_1 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:273:18, :276:7
  reg signed [31:0] outData_2;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:279:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:280:5
    outData_2 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:278:18, :281:7
  reg signed [31:0] outData_3;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:284:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:285:5
    outData_3 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:283:18, :286:7
  reg signed [31:0] outData_4;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:289:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:290:5
    outData_4 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:288:18, :291:7
  reg signed [31:0] outData_5;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:294:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:295:5
    outData_5 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:293:18, :296:7
  reg signed [31:0] outData_6;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:299:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:300:5
    outData_6 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:298:18, :301:7
  reg signed [31:0] outData_7;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:304:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:305:5
    outData_7 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:303:18, :306:7
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:309:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:310:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:308:18, :311:7
  reg        state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:316:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:317:5
    state_reg3 = 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:314:14, :318:7
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:322:5
    if (rst)	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:323:7
      state_reg3 <= 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:314:14, :324:9
    else begin	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:323:7
      case (state_reg3)	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:320:10, :326:9
        1'b0: begin
          mainResult <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:313:18, :328:11
          $write("%10d\n", 32'sh0);	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:313:18, :321:25, :329:11
          state_reg3 <= 1'h1;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:315:13, :330:11
        end
        1'b1:
          state_reg3 <= state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:320:10, :333:11
        default:
          state_reg3 <= state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:320:10, :336:11
      endcase	// /home/qinkejiu/mygo/tests/CHStone/mips/.mygo-tmp/.mygo-circt-2652196930/design.pipeline.mlir:320:10, :326:9
    end
  end // always @(posedge)
endmodule

