// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:2:36
);

  reg signed [7:0]  MVtab0_0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:4:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:5:5
    MVtab0_0 = 8'hFF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:3:15, :6:7
  reg signed [7:0]  MVtab0_1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:9:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:10:5
    MVtab0_1 = 8'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:8:14, :11:7
  reg signed [7:0]  MVtab0_10;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:14:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:15:5
    MVtab0_10 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:13:14, :16:7
  reg signed [7:0]  MVtab0_11;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:19:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:20:5
    MVtab0_11 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:18:16, :21:7
  reg signed [7:0]  MVtab0_12;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:24:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:25:5
    MVtab0_12 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:23:16, :26:7
  reg signed [7:0]  MVtab0_13;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:29:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:30:5
    MVtab0_13 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:28:16, :31:7
  reg signed [7:0]  MVtab0_14;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:34:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:35:5
    MVtab0_14 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:33:16, :36:7
  reg signed [7:0]  MVtab0_15;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:39:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:40:5
    MVtab0_15 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:38:16, :41:7
  reg signed [7:0]  MVtab0_2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:44:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:45:5
    MVtab0_2 = 8'h3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:43:14, :46:7
  reg signed [7:0]  MVtab0_3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:49:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:50:5
    MVtab0_3 = 8'h3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:48:16, :51:7
  reg signed [7:0]  MVtab0_4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:54:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:55:5
    MVtab0_4 = 8'h2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:53:14, :56:7
  reg signed [7:0]  MVtab0_5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:59:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:60:5
    MVtab0_5 = 8'h2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:58:16, :61:7
  reg signed [7:0]  MVtab0_6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:64:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:65:5
    MVtab0_6 = 8'h2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:63:16, :66:7
  reg signed [7:0]  MVtab0_7;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:69:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:70:5
    MVtab0_7 = 8'h2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:68:16, :71:7
  reg signed [7:0]  MVtab0_8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:74:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:75:5
    MVtab0_8 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:73:16, :76:7
  reg signed [7:0]  MVtab0_9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:79:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:80:5
    MVtab0_9 = 8'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:78:17, :81:7
  reg signed [7:0]  MVtab1_0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:84:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:85:5
    MVtab1_0 = 8'hFF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:83:18, :86:7
  reg signed [7:0]  MVtab1_1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:89:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:90:5
    MVtab1_1 = 8'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:88:17, :91:7
  reg signed [7:0]  MVtab1_10;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:94:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:95:5
    MVtab1_10 = 8'h5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:93:14, :96:7
  reg signed [7:0]  MVtab1_11;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:99:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:100:5
    MVtab1_11 = 8'h6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:98:14, :101:7
  reg signed [7:0]  MVtab1_12;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:104:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:105:5
    MVtab1_12 = 8'h4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:103:14, :106:7
  reg signed [7:0]  MVtab1_13;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:109:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:110:5
    MVtab1_13 = 8'h5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:108:17, :111:7
  reg signed [7:0]  MVtab1_14;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:114:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:115:5
    MVtab1_14 = 8'h4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:113:17, :116:7
  reg signed [7:0]  MVtab1_15;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:119:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:120:5
    MVtab1_15 = 8'h5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:118:17, :121:7
  reg signed [7:0]  MVtab1_2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:124:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:125:5
    MVtab1_2 = 8'hFF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:123:18, :126:7
  reg signed [7:0]  MVtab1_3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:129:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:130:5
    MVtab1_3 = 8'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:128:17, :131:7
  reg signed [7:0]  MVtab1_4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:134:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:135:5
    MVtab1_4 = 8'hFF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:133:18, :136:7
  reg signed [7:0]  MVtab1_5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:139:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:140:5
    MVtab1_5 = 8'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:138:17, :141:7
  reg signed [7:0]  MVtab1_6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:144:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:145:5
    MVtab1_6 = 8'h7;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:143:14, :146:7
  reg signed [7:0]  MVtab1_7;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:149:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:150:5
    MVtab1_7 = 8'h6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:148:17, :151:7
  reg signed [7:0]  MVtab1_8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:154:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:155:5
    MVtab1_8 = 8'h6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:153:17, :156:7
  reg signed [7:0]  MVtab1_9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:159:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:160:5
    MVtab1_9 = 8'h6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:158:17, :161:7
  reg signed [7:0]  MVtab2_0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:164:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:165:5
    MVtab2_0 = 8'h10;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:163:15, :166:7
  reg signed [7:0]  MVtab2_1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:169:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:170:5
    MVtab2_1 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:168:14, :171:7
  reg signed [7:0]  MVtab2_10;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:174:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:175:5
    MVtab2_10 = 8'hB;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:173:15, :176:7
  reg signed [7:0]  MVtab2_11;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:179:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:180:5
    MVtab2_11 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:178:17, :181:7
  reg signed [7:0]  MVtab2_12;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:184:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:185:5
    MVtab2_12 = 8'hA;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:183:15, :186:7
  reg signed [7:0]  MVtab2_13;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:189:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:190:5
    MVtab2_13 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:188:14, :191:7
  reg signed [7:0]  MVtab2_14;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:194:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:195:5
    MVtab2_14 = 8'hA;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:193:18, :196:7
  reg signed [7:0]  MVtab2_15;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:199:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:200:5
    MVtab2_15 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:198:17, :201:7
  reg signed [7:0]  MVtab2_16;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:204:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:205:5
    MVtab2_16 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:203:17, :206:7
  reg signed [7:0]  MVtab2_17;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:209:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:210:5
    MVtab2_17 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:208:17, :211:7
  reg signed [7:0]  MVtab2_18;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:214:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:215:5
    MVtab2_18 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:213:17, :216:7
  reg signed [7:0]  MVtab2_19;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:219:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:220:5
    MVtab2_19 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:218:17, :221:7
  reg signed [7:0]  MVtab2_2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:224:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:225:5
    MVtab2_2 = 8'hF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:223:15, :226:7
  reg signed [7:0]  MVtab2_20;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:229:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:230:5
    MVtab2_20 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:228:17, :231:7
  reg signed [7:0]  MVtab2_21;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:234:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:235:5
    MVtab2_21 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:233:17, :236:7
  reg signed [7:0]  MVtab2_22;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:239:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:240:5
    MVtab2_22 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:238:17, :241:7
  reg signed [7:0]  MVtab2_23;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:244:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:245:5
    MVtab2_23 = 8'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:243:17, :246:7
  reg signed [7:0]  MVtab2_3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:249:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:250:5
    MVtab2_3 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:248:17, :251:7
  reg signed [7:0]  MVtab2_4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:254:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:255:5
    MVtab2_4 = 8'hE;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:253:15, :256:7
  reg signed [7:0]  MVtab2_5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:259:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:260:5
    MVtab2_5 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:258:17, :261:7
  reg signed [7:0]  MVtab2_6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:264:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:265:5
    MVtab2_6 = 8'hD;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:263:15, :266:7
  reg signed [7:0]  MVtab2_7;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:269:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:270:5
    MVtab2_7 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:268:17, :271:7
  reg signed [7:0]  MVtab2_8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:274:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:275:5
    MVtab2_8 = 8'hC;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:273:15, :276:7
  reg signed [7:0]  MVtab2_9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:279:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:280:5
    MVtab2_9 = 8'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:278:17, :281:7
  reg signed [31:0] inPMV_0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:284:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:285:5
    inPMV_0 = 32'h2D;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:283:16, :286:7
  reg signed [31:0] inPMV_1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:289:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:290:5
    inPMV_1 = 32'hCF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:288:17, :291:7
  reg signed [31:0] inPMV_2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:294:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:295:5
    inPMV_2 = 32'h46;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:293:16, :296:7
  reg signed [31:0] inPMV_3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:299:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:300:5
    inPMV_3 = 32'h29;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:298:16, :301:7
  reg signed [31:0] inPMV_4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:304:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:305:5
    inPMV_4 = 32'h4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:303:15, :306:7
  reg signed [31:0] inPMV_5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:309:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:310:5
    inPMV_5 = 32'hB4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:308:17, :311:7
  reg signed [31:0] inPMV_6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:314:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:315:5
    inPMV_6 = 32'h78;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:313:17, :316:7
  reg signed [31:0] inPMV_7;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:319:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:320:5
    inPMV_7 = 32'hD8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:318:17, :321:7
  reg signed [31:0] inmvfs_0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:324:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:325:5
    inmvfs_0 = 32'hE8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:323:17, :326:7
  reg signed [31:0] inmvfs_1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:329:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:330:5
    inmvfs_1 = 32'hC8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:328:17, :331:7
  reg signed [31:0] inmvfs_2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:334:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:335:5
    inmvfs_2 = 32'h20;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:333:16, :336:7
  reg signed [31:0] inmvfs_3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:339:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:340:5
    inmvfs_3 = 32'hF0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:338:17, :341:7
  reg signed [31:0] outPMV_0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:344:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:345:5
    outPMV_0 = 32'h2D;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:343:19, :346:7
  reg signed [31:0] outPMV_1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:349:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:350:5
    outPMV_1 = 32'hCE;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:348:17, :351:7
  reg signed [31:0] outPMV_2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:354:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:355:5
    outPMV_2 = 32'h46;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:353:19, :356:7
  reg signed [31:0] outPMV_3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:359:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:360:5
    outPMV_3 = 32'h29;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:358:19, :361:7
  reg signed [31:0] outPMV_4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:364:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:365:5
    outPMV_4 = 32'h2D;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:363:19, :366:7
  reg signed [31:0] outPMV_5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:369:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:370:5
    outPMV_5 = 32'hCE;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:368:20, :371:7
  reg signed [31:0] outPMV_6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:374:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:375:5
    outPMV_6 = 32'h78;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:373:20, :376:7
  reg signed [31:0] outPMV_7;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:379:17
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:380:5
    outPMV_7 = 32'hD8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:378:20, :381:7
  reg signed [31:0] outmvfs_0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:384:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:385:5
    outmvfs_0 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:383:15, :386:7
  reg signed [31:0] outmvfs_1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:389:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:390:5
    outmvfs_1 = 32'hC8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:388:20, :391:7
  reg signed [31:0] outmvfs_2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:394:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:395:5
    outmvfs_2 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:393:18, :396:7
  reg signed [31:0] outmvfs_3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:399:18
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:400:5
    outmvfs_3 = 32'hF0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:398:20, :401:7
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:404:16
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:405:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:403:18, :406:7
  reg        state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:411:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:412:5
    state_reg3 = 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:409:14, :413:7
  reg signed [31:0] print_reg5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:416:19
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:418:5
    print_reg5 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:417:18, :419:7
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:422:5
    if (rst)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:423:7
      state_reg3 <= 1'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:409:14, :424:9
    else begin	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:423:7
      case (state_reg3)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:415:10, :426:9
        1'b0: begin
          print_reg5 = 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:408:18, :428:11
          $write("%0d\n", print_reg5);	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:421:25, :429:16, :430:11
          state_reg3 <= 1'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:410:13, :431:11
        end
        1'b1:
          state_reg3 <= state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:415:10, :434:11
        default:
          state_reg3 <= state_reg3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:415:10, :437:11
      endcase	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1033726650/design.pipeline.mlir:415:10, :426:9
    end
  end // always @(posedge)
endmodule

