// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:3
  input        clk,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:22
               rst,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:36
  input signed [31:0] inmvfs_0,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:50
               inmvfs_1,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:70
               inPMV_0,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:90
               inPMV_1,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:109
               outmvfs_0,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:128
               outmvfs_1,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:149
               outPMV_0,	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:170
               outPMV_1	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:2:190
);

  reg  [4:0]  state_reg107;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:110:21
  initial	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:111:5
    state_reg107 = 5'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:86:14, :112:7
  reg  [31:0] reg110;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:115:15
  always_ff @(posedge clk)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:117:5
    reg110 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:83:18, :118:7
  reg  [31:0] reg111;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:120:15
  always_ff @(posedge clk)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:122:5
    reg111 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:85:18, :123:7
  reg  [31:0] phi_reg112;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:125:19
  reg signed [31:0] phi_reg119;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:132:19
  reg  [31:0] phi_reg121;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:134:19
  reg  [31:0] phi_reg124;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:137:19
  reg  [31:0] phi_reg126;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:139:19
  reg  [31:0] phi_reg140;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:153:19
  reg  [31:0] phi_reg142;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:155:19
  reg  [31:0] phi_reg144;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:157:19
  reg  [31:0] phi_reg162;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:175:19
  reg  [31:0] phi_reg169;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:182:19
  wire [31:0] _GEN = phi_reg169 == 32'h1 ? 32'h0 : 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:23:18, :24:18, :25:18, :183:11, :188:11, :189:11
  reg  [31:0] phi_reg181;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:194:19
  wire [31:0] _GEN_0 = phi_reg181 == 32'h1 ? 32'h0 : 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:37:18, :38:18, :39:18, :195:11, :202:11, :203:11
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:210:5
    if (rst)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:211:7
      state_reg107 <= 5'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:86:14, :212:9
    else begin	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:211:7
      case (state_reg107)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:114:10, :214:9
        5'b00000: begin
          state_reg107 <= 5'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:87:14, :216:11
          phi_reg112 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:3:15, :217:11
        end
        5'b00001: begin
          if ($signed(phi_reg112) < 32'sh2)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:4:15, :126:10, :127:10, :220:11
            state_reg107 <= 5'h10;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:102:16, :221:13
          else	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:220:11
            state_reg107 <= 5'h2;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:88:14, :223:13
        end
        5'b00010: begin
          state_reg107 <= 5'h3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:89:14, :227:11
          phi_reg119 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:46:18, :228:11
          phi_reg121 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:47:18, :229:11
        end
        5'b00011: begin
          if ($signed(phi_reg121) < 32'sh2)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:48:18, :135:11, :136:11, :232:11
            state_reg107 <= 5'h5;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:91:14, :233:13
          else	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:232:11
            state_reg107 <= 5'h4;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:90:14, :235:13
        end
        5'b00100: begin
          $fwrite(32'h80000001, "%d\n", phi_reg119);	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:133:10, :209:25, :239:11
          state_reg107 <= 5'h17;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:109:15, :240:11
        end
        5'b00101: begin
          state_reg107 <= 5'h6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:92:14, :243:11
          phi_reg124 <= phi_reg119;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:133:10, :244:11
          phi_reg126 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:49:18, :245:11
        end
        5'b00110: begin
          if ($signed(phi_reg126) < 32'sh2)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:50:18, :140:11, :141:11, :248:11
            state_reg107 <= 5'h8;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:94:14, :249:13
          else	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:248:11
            state_reg107 <= 5'h7;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:93:14, :251:13
        end
        5'b00111: begin
          state_reg107 <= 5'h3;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:89:14, :255:11
          phi_reg119 <= phi_reg124;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:138:11, :256:11
          phi_reg121 <= phi_reg121 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:61:18, :135:11, :142:11, :257:11
        end
        5'b01000: begin
          if ((phi_reg126 == 32'h1
                 ? 32'h0
                 : 32'h0) != (phi_reg126 == 32'h1 ? 32'h0 : 32'h0))	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:54:18, :55:18, :56:18, :58:18, :59:18, :60:18, :140:11, :145:11, :146:11, :149:11, :150:11, :151:11, :260:11
            state_reg107 <= 5'h9;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:95:14, :261:13
          else begin	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:260:11
            state_reg107 <= 5'hA;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:96:15, :263:13
            phi_reg140 <= phi_reg124;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:138:11, :264:13
          end
        end
        5'b01001: begin
          state_reg107 <= 5'hA;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:96:15, :268:11
          phi_reg140 <= phi_reg124 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:62:18, :138:11, :152:11, :269:11
        end
        5'b01010: begin
          state_reg107 <= 5'hB;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:97:15, :272:11
          phi_reg142 <= phi_reg140;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:154:11, :273:11
          phi_reg144 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:63:18, :274:11
        end
        5'b01011: begin
          if ($signed(phi_reg144) < 32'sh2)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:64:18, :158:11, :159:11, :277:11
            state_reg107 <= 5'hD;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:99:15, :278:13
          else	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:277:11
            state_reg107 <= 5'hC;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:98:15, :280:13
        end
        5'b01100: begin
          state_reg107 <= 5'h6;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:92:14, :284:11
          phi_reg124 <= phi_reg142;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:156:11, :285:11
          phi_reg126 <= phi_reg126 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:79:18, :140:11, :160:11, :286:11
        end
        5'b01101: begin
          if ((phi_reg144 == 32'h1
                 ? 32'h0
                 : 32'h0) != (phi_reg144 == 32'h1 ? 32'h0 : 32'h0))	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:69:18, :70:18, :71:18, :76:18, :77:18, :78:18, :158:11, :165:11, :166:11, :171:11, :172:11, :173:11, :289:11
            state_reg107 <= 5'hE;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:100:15, :290:13
          else begin	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:289:11
            state_reg107 <= 5'hF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:101:15, :292:13
            phi_reg162 <= phi_reg142;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:156:11, :293:13
          end
        end
        5'b01110: begin
          state_reg107 <= 5'hF;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:101:15, :297:11
          phi_reg162 <= phi_reg142 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:80:18, :156:11, :174:11, :298:11
        end
        5'b01111: begin
          state_reg107 <= 5'hB;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:97:15, :301:11
          phi_reg142 <= phi_reg162;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:176:11, :302:11
          phi_reg144 <= phi_reg144 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:81:18, :158:11, :177:11, :303:11
        end
        5'b10000: begin
          state_reg107 <= 5'h11;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:103:16, :306:11
          phi_reg169 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:20:18, :307:11
        end
        5'b10001: begin
          if ($signed(phi_reg169) < 32'sh2)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:21:18, :183:11, :184:11, :310:11
            state_reg107 <= 5'h13;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:105:16, :311:13
          else	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:310:11
            state_reg107 <= 5'h12;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:104:16, :313:13
        end
        5'b10010: begin
          state_reg107 <= 5'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:87:14, :317:11
          phi_reg112 <= phi_reg112 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:30:18, :126:10, :185:11, :318:11
        end
        5'b10011: begin
          state_reg107 <= 5'h14;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:106:16, :321:11
          phi_reg181 <= 32'h0;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:31:18, :322:11
        end
        5'b10100: begin
          if ($signed(phi_reg181) < 32'sh2)	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:32:18, :195:11, :196:11, :325:11
            state_reg107 <= 5'h16;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:108:16, :326:13
          else	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:325:11
            state_reg107 <= 5'h15;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:107:16, :328:13
        end
        5'b10101: begin
          state_reg107 <= 5'h11;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:103:16, :332:11
          phi_reg169 <= phi_reg169 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:45:18, :183:11, :197:11, :333:11
        end
        5'b10110: begin
          state_reg107 <= 5'h14;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:106:16, :336:11
          phi_reg181 <= phi_reg181 + 32'h1;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:44:18, :195:11, :208:11, :337:11
        end
        5'b10111:
          state_reg107 <= state_reg107;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:114:10, :340:11
        default:
          state_reg107 <= state_reg107;	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:114:10, :343:11
      endcase	// /home/qinkejiu/mygo/tests/CHStone/motion/.mygo-tmp/.mygo-circt-1045609415/design.pipeline.mlir:114:10, :214:9
    end
  end // always @(posedge)
endmodule


// mygo autogenerated loop FSM fallback modules
module main__proc_main__loop0_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t5_2138
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule

module main__proc_main__loop1_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t35_2234
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule

module main__proc_main__loop2_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t43_2242
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule

module main__proc_main__loop3_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t56_2272
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule

module main__proc_main__loop4_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t15_2179
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule

module main__proc_main__loop5_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t23_2202
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule
