// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/CHStone/common/.mygo-tmp/.mygo-circt-566470805/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/CHStone/common/.mygo-tmp/.mygo-circt-566470805/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/CHStone/common/.mygo-tmp/.mygo-circt-566470805/design.pipeline.mlir:2:36
);

endmodule

