// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:2:36
);

  wire signed [31:0] chan_t0_wdata;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:3:22
  wire        chan_t0_wvalid;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:4:23
  wire        chan_t0_wready;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:5:23
  wire signed [31:0] chan_t0_rdata;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:6:22
  wire        chan_t0_rvalid;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:7:23
  wire        chan_t0_rready;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:8:23
  wire        chan_t0_full;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:9:21
  wire        chan_t0_almost_full;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:10:28
  wire        chan_t0_empty;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:11:22
  wire        chan_t0_almost_empty;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:12:29
  wire signed [31:0] chan_t1_wdata;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:13:22
  wire        chan_t1_wvalid;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:14:23
  wire        chan_t1_wready;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:15:23
  wire signed [31:0] chan_t1_rdata;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:16:22
  wire        chan_t1_rvalid;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:17:23
  wire        chan_t1_rready;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:18:23
  wire        chan_t1_full;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:19:21
  wire        chan_t1_almost_full;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:20:28
  wire        chan_t1_empty;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:21:22
  wire        chan_t1_almost_empty;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:22:29
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(4), .ADDR_WIDTH(2), .COUNT_WIDTH(3), .LAST_PTR_VALUE(3), .DEPTH_COUNT_VALUE(4), .ALMOST_FULL_LEVEL(3), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(3), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t0_fifo (	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:25:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:24:10
    .wr_en        (chan_t0_wvalid),
    .wr_data      (chan_t0_wdata),
    .full         (chan_t0_full),
    .almost_full  (chan_t0_almost_full),
    .rd_en        (chan_t0_rready),
    .rd_data      (chan_t0_rdata),
    .empty        (chan_t0_empty),
    .almost_empty (chan_t0_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:25:5
  assign chan_t0_wready = ~chan_t0_full;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:26:10, :27:10, :28:5
  assign chan_t0_rvalid = ~chan_t0_empty;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:29:10, :30:10, :31:5
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(4), .ADDR_WIDTH(2), .COUNT_WIDTH(3), .LAST_PTR_VALUE(3), .DEPTH_COUNT_VALUE(4), .ALMOST_FULL_LEVEL(3), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(3), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t1_fifo (	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:34:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:33:10
    .wr_en        (chan_t1_wvalid),
    .wr_data      (chan_t1_wdata),
    .full         (chan_t1_full),
    .almost_full  (chan_t1_almost_full),
    .rd_en        (chan_t1_rready),
    .rd_data      (chan_t1_rdata),
    .empty        (chan_t1_empty),
    .almost_empty (chan_t1_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:34:5
  assign chan_t1_wready = ~chan_t1_full;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:35:10, :36:10, :37:5
  assign chan_t1_rvalid = ~chan_t1_empty;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:38:10, :39:10, :40:5
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:42:16
  initial	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:43:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:41:15, :44:7
  reg  [2:0]  state_reg7;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:53:19
  initial	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:54:5
    state_reg7 = 3'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:47:14, :55:7
  reg  [31:0] recv_reg9;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:58:18
  reg signed [31:0] print_reg11;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:60:20
  initial	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:62:5
    print_reg11 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:61:17, :63:7
  assign chan_t0_wvalid = state_reg7 == 3'h1;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:48:14, :57:11, :66:11, :68:5
  assign chan_t0_wdata = chan_t0_wvalid ? 32'h5 : 32'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:4:23, :46:15, :69:17, :70:11, :71:5
  assign chan_t1_rready = state_reg7 == 3'h3;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:50:14, :57:11, :67:11, :73:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:76:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:77:7
      state_reg7 <= 3'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:47:14, :78:9
    else begin	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:77:7
      case (state_reg7)	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:57:11, :80:9
        3'b000:
          state_reg7 <= 3'h1;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:48:14, :82:11
        3'b001: begin
          if (chan_t0_wready)	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:72:11, :85:11
            state_reg7 <= 3'h2;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:49:14, :86:13
          else	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:85:11
            state_reg7 <= state_reg7;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:57:11, :88:13
        end
        3'b010:
          state_reg7 <= 3'h3;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:50:14, :92:11
        3'b011: begin
          if (chan_t1_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:74:11, :95:11
            recv_reg9 <= chan_t1_rdata;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:75:11, :96:13
            state_reg7 <= 3'h4;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:51:15, :97:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:95:11
            state_reg7 <= state_reg7;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:57:11, :99:13
        end
        3'b100: begin
          print_reg11 = recv_reg9;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:59:11, :103:11
          $write("main observed=%0d\n", print_reg11);	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:65:25, :104:17, :105:11
          state_reg7 <= 3'h5;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:52:15, :106:11
        end
        3'b101:
          state_reg7 <= state_reg7;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:57:11, :109:11
        default:
          state_reg7 <= state_reg7;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:57:11, :112:11
      endcase	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:57:11, :80:9
    end
  end // always @(posedge)
  main__proc_worker worker_inst0 (	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:116:5
    .clk            (clk),
    .rst            (rst),
    .chan_t0_rdata  (chan_t0_rdata),
    .chan_t0_rvalid (chan_t0_rvalid),
    .chan_t0_rready (chan_t0_rready),
    .chan_t1_wdata  (chan_t1_wdata),
    .chan_t1_wvalid (chan_t1_wvalid),
    .chan_t1_wready (chan_t1_wready)
  );	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:116:5
endmodule

module main__proc_worker(	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:35
               rst,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:49
  inout [31:0] chan_t0_rdata,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:66
  inout        chan_t0_rvalid,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:94
               chan_t0_rready,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:122
  inout [31:0] chan_t1_wdata,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:150
  inout        chan_t1_wvalid,	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:178
               chan_t1_wready	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:206
);

  reg  [2:0]  state_reg29;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:127:20
  initial	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:128:5
    state_reg29 = 3'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:121:14, :129:7
  reg  [31:0] recv_reg31;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:132:19
  reg signed [31:0] print_reg33;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:134:20
  initial	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:136:5
    print_reg33 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:135:15, :137:7
  reg signed [31:0] print_reg35;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:139:20
  initial	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:141:5
    print_reg35 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:140:17, :142:7
  wire [31:0] _GEN = recv_reg31 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:120:15, :133:10, :144:10
  assign chan_t1_wvalid = state_reg29 == 3'h3;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:124:14, :131:10, :146:10, :148:5
  assign chan_t1_wdata = chan_t1_wvalid ? _GEN : 32'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:119:178, :144:10, :149:17, :150:10, :151:5
  assign chan_t0_rready = state_reg29 == 3'h1;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:122:14, :131:10, :147:10, :153:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:156:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:157:7
      state_reg29 <= 3'h0;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:121:14, :158:9
    else begin	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:157:7
      case (state_reg29)	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:131:10, :160:9
        3'b000:
          state_reg29 <= 3'h1;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:122:14, :162:11
        3'b001: begin
          if (chan_t0_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:154:10, :165:11
            recv_reg31 <= chan_t0_rdata;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:155:10, :166:13
            state_reg29 <= 3'h2;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:123:14, :167:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:165:11
            state_reg29 <= state_reg29;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:131:10, :169:13
        end
        3'b010:
          state_reg29 <= 3'h3;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:124:14, :173:11
        3'b011: begin
          if (chan_t1_wready)	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:152:10, :176:11
            state_reg29 <= 3'h4;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:125:15, :177:13
          else	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:176:11
            state_reg29 <= state_reg29;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:131:10, :179:13
        end
        3'b100: begin
          print_reg33 = recv_reg31;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:133:10, :183:11
          print_reg35 = _GEN;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:144:10, :185:11
          $write("worker received=%0d produced=%0d\n", print_reg33,
                  print_reg35);	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:145:25, :184:16, :186:17, :187:11
          state_reg29 <= 3'h5;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:126:15, :188:11
        end
        3'b101:
          state_reg29 <= state_reg29;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:131:10, :191:11
        default:
          state_reg29 <= state_reg29;	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:131:10, :194:11
      endcase	// /home/qinkejiu/mygo/tests/stages/simple_channel/.mygo-tmp/.mygo-circt-1884059971/design.pipeline.mlir:131:10, :160:9
    end
  end // always @(posedge)
endmodule


module mygo_fifo #(
  parameter integer DATA_WIDTH = 32,
  parameter integer DEPTH = 1,
  parameter integer ADDR_WIDTH = 1,
  parameter integer COUNT_WIDTH = 1,
  parameter integer LAST_PTR_VALUE = 0,
  parameter integer DEPTH_COUNT_VALUE = 1,
  parameter integer ALMOST_FULL_LEVEL = 1,
  parameter integer ALMOST_EMPTY_LEVEL = 0,
  parameter integer ALMOST_FULL_COUNT_VALUE = 1,
  parameter integer ALMOST_EMPTY_COUNT_VALUE = 0,
  parameter bit USE_REGISTERED_READ = 1'b0,
  parameter bit ALMOST_EMPTY_USES_EMPTY = 1'b1,
  parameter bit ASYNC_RESET = 1'b0
) (
  input  wire                   clk,
  input  wire                   rst_n,
  input  wire                   wr_en,
  input  wire [DATA_WIDTH-1:0]  wr_data,
  output wire                   full,
  output wire                   almost_full,
  input  wire                   rd_en,
  output wire [DATA_WIDTH-1:0]  rd_data,
  output wire                   empty,
  output wire                   almost_empty
);

  localparam [ADDR_WIDTH-1:0] LAST_PTR = ADDR_WIDTH'(LAST_PTR_VALUE);
  localparam [COUNT_WIDTH-1:0] DEPTH_COUNT = COUNT_WIDTH'(DEPTH_COUNT_VALUE);
  localparam [COUNT_WIDTH-1:0] ALMOST_FULL_COUNT = COUNT_WIDTH'(ALMOST_FULL_COUNT_VALUE);
  localparam [COUNT_WIDTH-1:0] ALMOST_EMPTY_COUNT = COUNT_WIDTH'(ALMOST_EMPTY_COUNT_VALUE);

  reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];
  reg [ADDR_WIDTH-1:0] wr_ptr;
  reg [ADDR_WIDTH-1:0] rd_ptr;
  reg [COUNT_WIDTH-1:0] count;

  wire wr_fire = wr_en && !full;
  wire rd_fire = rd_en && !empty;
  wire [ADDR_WIDTH-1:0] wr_ptr_next = (wr_ptr == LAST_PTR) ? {ADDR_WIDTH{1'b0}} : (wr_ptr + 1'b1);
  wire [ADDR_WIDTH-1:0] rd_ptr_next = (rd_ptr == LAST_PTR) ? {ADDR_WIDTH{1'b0}} : (rd_ptr + 1'b1);

  assign full = (count == DEPTH_COUNT);
  assign empty = (count == {COUNT_WIDTH{1'b0}});
  assign almost_full = (count >= ALMOST_FULL_COUNT);
  assign almost_empty = (ALMOST_EMPTY_USES_EMPTY != 1'b0) ? empty : (count <= ALMOST_EMPTY_COUNT);

  generate
    if (USE_REGISTERED_READ != 1'b0) begin : gen_registered_read
      reg [DATA_WIDTH-1:0] rd_data_reg;
      assign rd_data = empty ? {DATA_WIDTH{1'b0}} : rd_data_reg;

      if (ASYNC_RESET != 1'b0) begin : gen_async_reset
        always @(posedge clk or negedge rst_n) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
            rd_data_reg <= {DATA_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
            if (empty && wr_fire) begin
              rd_data_reg <= wr_data;
            end else if (rd_fire) begin
              if (count > 1) begin
                rd_data_reg <= mem[rd_ptr_next];
              end else if (wr_fire) begin
                rd_data_reg <= wr_data;
              end else begin
                rd_data_reg <= {DATA_WIDTH{1'b0}};
              end
            end else if (!empty) begin
              rd_data_reg <= mem[rd_ptr];
            end
          end
        end
      end else begin : gen_sync_reset
        always @(posedge clk) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
            rd_data_reg <= {DATA_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
            if (empty && wr_fire) begin
              rd_data_reg <= wr_data;
            end else if (rd_fire) begin
              if (count > 1) begin
                rd_data_reg <= mem[rd_ptr_next];
              end else if (wr_fire) begin
                rd_data_reg <= wr_data;
              end else begin
                rd_data_reg <= {DATA_WIDTH{1'b0}};
              end
            end else if (!empty) begin
              rd_data_reg <= mem[rd_ptr];
            end
          end
        end
      end
    end else begin : gen_direct_read
      assign rd_data = empty ? {DATA_WIDTH{1'b0}} : mem[rd_ptr];

      if (ASYNC_RESET != 1'b0) begin : gen_async_reset
        always @(posedge clk or negedge rst_n) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
          end
        end
      end else begin : gen_sync_reset
        always @(posedge clk) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
          end
        end
      end
    end
  endgenerate
endmodule
