// Generated by CIRCT firtool-1.106.0
module main(	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:2:3
  input clk,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:2:22
        rst	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:2:36
);

  wire [31:0] chan_t0_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:3:22
  wire        chan_t0_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:4:23
  wire        chan_t0_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:5:23
  wire [31:0] chan_t0_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:6:22
  wire        chan_t0_rvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:7:23
  wire        chan_t0_rready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:8:23
  wire        chan_t0_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:9:21
  wire        chan_t0_almost_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:10:28
  wire        chan_t0_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:11:22
  wire        chan_t0_almost_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:12:29
  wire [31:0] chan_t1_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:13:22
  wire        chan_t1_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:14:23
  wire        chan_t1_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:15:23
  wire [31:0] chan_t1_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:16:22
  wire        chan_t1_rvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:17:23
  wire        chan_t1_rready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:18:23
  wire        chan_t1_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:19:21
  wire        chan_t1_almost_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:20:28
  wire        chan_t1_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:21:22
  wire        chan_t1_almost_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:22:29
  wire [31:0] chan_t2_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:23:22
  wire        chan_t2_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:24:23
  wire        chan_t2_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:25:23
  wire [31:0] chan_t2_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:26:22
  wire        chan_t2_rvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:27:23
  wire        chan_t2_rready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:28:23
  wire        chan_t2_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:29:21
  wire        chan_t2_almost_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:30:28
  wire        chan_t2_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:31:22
  wire        chan_t2_almost_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:32:29
  wire [31:0] chan_t3_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:33:22
  wire        chan_t3_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:34:23
  wire        chan_t3_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:35:23
  wire [31:0] chan_t3_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:36:22
  wire        chan_t3_rvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:37:23
  wire        chan_t3_rready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:38:23
  wire        chan_t3_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:39:21
  wire        chan_t3_almost_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:40:28
  wire        chan_t3_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:41:22
  wire        chan_t3_almost_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:42:29
  wire        chan_t4_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:43:22
  wire        chan_t4_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:44:23
  wire        chan_t4_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:45:23
  wire        chan_t4_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:46:22
  wire        chan_t4_rvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:47:23
  wire        chan_t4_rready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:48:23
  wire        chan_t4_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:49:21
  wire        chan_t4_almost_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:50:28
  wire        chan_t4_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:51:22
  wire        chan_t4_almost_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:52:29
  wire        chan_t4_prod0_consumer0_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:53:38
  wire        chan_t4_prod0_consumer0_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:54:39
  wire        chan_t4_prod0_consumer0_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:55:39
  wire        chan_t4_prod1_consumer1_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:56:38
  wire        chan_t4_prod1_consumer1_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:57:39
  wire        chan_t4_prod1_consumer1_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:58:39
  wire        chan_t4_prod2_router_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:59:35
  wire        chan_t4_prod2_router_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:60:36
  wire        chan_t4_prod2_router_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:61:36
  wire        chan_t4_prod3_producer0_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:62:38
  wire        chan_t4_prod3_producer0_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:63:39
  wire        chan_t4_prod3_producer0_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:64:39
  wire        chan_t4_prod4_producer1_wdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:65:38
  wire        chan_t4_prod4_producer1_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:66:39
  wire        chan_t4_prod4_producer1_wready;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:67:39
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(2), .ADDR_WIDTH(1), .COUNT_WIDTH(2), .LAST_PTR_VALUE(1), .DEPTH_COUNT_VALUE(2), .ALMOST_FULL_LEVEL(1), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(1), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t0_fifo (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:70:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:69:10
    .wr_en        (chan_t0_wvalid),
    .wr_data      (chan_t0_wdata),
    .full         (chan_t0_full),
    .almost_full  (chan_t0_almost_full),
    .rd_en        (chan_t0_rready),
    .rd_data      (chan_t0_rdata),
    .empty        (chan_t0_empty),
    .almost_empty (chan_t0_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:70:5
  assign chan_t0_wready = ~chan_t0_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:71:10, :72:10, :73:5
  assign chan_t0_rvalid = ~chan_t0_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:74:10, :75:10, :76:5
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(2), .ADDR_WIDTH(1), .COUNT_WIDTH(2), .LAST_PTR_VALUE(1), .DEPTH_COUNT_VALUE(2), .ALMOST_FULL_LEVEL(1), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(1), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t1_fifo (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:79:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:78:10
    .wr_en        (chan_t1_wvalid),
    .wr_data      (chan_t1_wdata),
    .full         (chan_t1_full),
    .almost_full  (chan_t1_almost_full),
    .rd_en        (chan_t1_rready),
    .rd_data      (chan_t1_rdata),
    .empty        (chan_t1_empty),
    .almost_empty (chan_t1_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:79:5
  assign chan_t1_wready = ~chan_t1_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:80:10, :81:10, :82:5
  assign chan_t1_rvalid = ~chan_t1_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:83:10, :84:10, :85:5
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(2), .ADDR_WIDTH(1), .COUNT_WIDTH(2), .LAST_PTR_VALUE(1), .DEPTH_COUNT_VALUE(2), .ALMOST_FULL_LEVEL(1), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(1), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t2_fifo (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:88:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:87:11
    .wr_en        (chan_t2_wvalid),
    .wr_data      (chan_t2_wdata),
    .full         (chan_t2_full),
    .almost_full  (chan_t2_almost_full),
    .rd_en        (chan_t2_rready),
    .rd_data      (chan_t2_rdata),
    .empty        (chan_t2_empty),
    .almost_empty (chan_t2_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:88:5
  assign chan_t2_wready = ~chan_t2_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:89:11, :90:11, :91:5
  assign chan_t2_rvalid = ~chan_t2_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:92:11, :93:11, :94:5
  mygo_fifo #(.DATA_WIDTH(32), .DEPTH(2), .ADDR_WIDTH(1), .COUNT_WIDTH(2), .LAST_PTR_VALUE(1), .DEPTH_COUNT_VALUE(2), .ALMOST_FULL_LEVEL(1), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(1), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t3_fifo (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:97:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:96:11
    .wr_en        (chan_t3_wvalid),
    .wr_data      (chan_t3_wdata),
    .full         (chan_t3_full),
    .almost_full  (chan_t3_almost_full),
    .rd_en        (chan_t3_rready),
    .rd_data      (chan_t3_rdata),
    .empty        (chan_t3_empty),
    .almost_empty (chan_t3_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:97:5
  assign chan_t3_wready = ~chan_t3_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:98:11, :99:11, :100:5
  assign chan_t3_rvalid = ~chan_t3_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:101:11, :102:11, :103:5
  mygo_fifo #(.DATA_WIDTH(1), .DEPTH(5), .ADDR_WIDTH(3), .COUNT_WIDTH(3), .LAST_PTR_VALUE(4), .DEPTH_COUNT_VALUE(5), .ALMOST_FULL_LEVEL(4), .ALMOST_EMPTY_LEVEL(1), .ALMOST_FULL_COUNT_VALUE(4), .ALMOST_EMPTY_COUNT_VALUE(1), .USE_REGISTERED_READ(0), .ALMOST_EMPTY_USES_EMPTY(0), .ASYNC_RESET(0)) t4_fifo (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:106:5
    .clk          (clk),
    .rst_n        (~rst),	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:105:11
    .wr_en        (chan_t4_wvalid),
    .wr_data      (chan_t4_wdata),
    .full         (chan_t4_full),
    .almost_full  (chan_t4_almost_full),
    .rd_en        (chan_t4_rready),
    .rd_data      (chan_t4_rdata),
    .empty        (chan_t4_empty),
    .almost_empty (chan_t4_almost_empty)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:106:5
  wire        _GEN = ~chan_t4_full;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:107:11, :108:11
  wire        _GEN_0 = chan_t4_prod1_consumer1_wvalid & ~chan_t4_prod0_consumer0_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:109:11, :111:11, :113:11, :114:11
  wire        _GEN_1 = chan_t4_prod0_consumer0_wvalid | chan_t4_prod1_consumer1_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:109:11, :111:11, :115:11
  wire        _GEN_2 = chan_t4_prod2_router_wvalid & ~_GEN_1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:115:11, :116:11, :118:11, :119:11
  wire        _GEN_3 = _GEN_1 | chan_t4_prod2_router_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:115:11, :116:11, :120:11
  wire        _GEN_4 = chan_t4_prod3_producer0_wvalid & ~_GEN_3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:120:11, :121:11, :123:11, :124:11
  wire        _GEN_5 = _GEN_3 | chan_t4_prod3_producer0_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:120:11, :121:11, :125:11
  wire        _GEN_6 = chan_t4_prod4_producer1_wvalid & ~_GEN_5;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:125:11, :126:11, :128:11, :129:11
  assign chan_t4_wvalid =
    chan_t4_prod0_consumer0_wvalid | chan_t4_prod1_consumer1_wvalid
    | chan_t4_prod2_router_wvalid | chan_t4_prod3_producer0_wvalid
    | chan_t4_prod4_producer1_wvalid;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:109:11, :111:11, :116:11, :121:11, :126:11, :131:11, :132:11, :133:11, :134:11, :135:5
  assign chan_t4_wdata =
    chan_t4_prod0_consumer0_wvalid
      ? chan_t4_prod0_consumer0_wdata
      : _GEN_0
          ? chan_t4_prod1_consumer1_wdata
          : _GEN_2
              ? chan_t4_prod2_router_wdata
              : _GEN_4
                  ? chan_t4_prod3_producer0_wdata
                  : _GEN_6 ? chan_t4_prod4_producer1_wdata : 1'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:109:11, :110:11, :112:11, :114:11, :117:11, :119:11, :122:11, :124:11, :127:11, :129:11, :136:14, :137:11, :138:11, :139:11, :140:11, :141:11, :142:5
  assign chan_t4_prod0_consumer0_wready = chan_t4_prod0_consumer0_wvalid & _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:108:11, :109:11, :143:11, :144:5
  assign chan_t4_prod1_consumer1_wready = _GEN_0 & _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:108:11, :114:11, :145:11, :146:5
  assign chan_t4_prod2_router_wready = _GEN_2 & _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:108:11, :119:11, :147:11, :148:5
  assign chan_t4_prod3_producer0_wready = _GEN_4 & _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:108:11, :124:11, :149:11, :150:5
  assign chan_t4_prod4_producer1_wready = _GEN_6 & _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:108:11, :129:11, :151:11, :152:5
  assign chan_t4_rvalid = ~chan_t4_empty;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:153:11, :154:11, :155:5
  reg signed [31:0] varargs;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:157:16
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:158:5
    varargs = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:156:15, :159:7
  reg  [2:0]  state_reg48;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:172:20
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:173:5
    state_reg48 = 3'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:165:14, :174:7
  reg         recv_reg50;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:177:19
  reg signed [31:0] print_reg52;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:179:20
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:181:5
    print_reg52 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:180:17, :182:7
  reg  [31:0] phi_reg54;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:184:18
  assign chan_t4_rready = state_reg48 == 3'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:169:15, :176:11, :189:11, :190:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:193:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:194:7
      state_reg48 <= 3'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:165:14, :195:9
    else begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:194:7
      case (state_reg48)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:176:11, :197:9
        3'b000: begin
          state_reg48 <= 3'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:166:14, :199:11
          phi_reg54 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:161:17, :200:11
        end
        3'b001: begin
          if ($signed(phi_reg54) < 32'sh5)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:162:15, :185:11, :186:11, :203:11
            state_reg48 <= 3'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:168:14, :204:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:203:11
            state_reg48 <= 3'h2;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:167:14, :206:13
        end
        3'b010: begin
          print_reg52 = 32'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:164:15, :210:11
          $write("router complete packets=%0d\n", print_reg52);	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:188:25, :211:17, :212:11
          state_reg48 <= 3'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:171:15, :213:11
        end
        3'b011:
          state_reg48 <= 3'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:169:15, :216:11
        3'b100: begin
          if (chan_t4_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:191:11, :219:11
            recv_reg50 <= chan_t4_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:192:11, :220:13
            state_reg48 <= 3'h5;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:170:15, :221:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:219:11
            state_reg48 <= state_reg48;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:176:11, :223:13
        end
        3'b101: begin
          state_reg48 <= 3'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:166:14, :227:11
          phi_reg54 <= phi_reg54 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:163:15, :185:11, :187:11, :228:11
        end
        3'b110:
          state_reg48 <= state_reg48;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:176:11, :231:11
        default:
          state_reg48 <= state_reg48;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:176:11, :234:11
      endcase	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:176:11, :197:9
    end
  end // always @(posedge)
  main__proc_consumer0 consumer0_inst0 (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:238:5
    .clk            (clk),
    .rst            (rst),
    .chan_t2_rdata  (chan_t2_rdata),
    .chan_t2_rvalid (chan_t2_rvalid),
    .chan_t2_rready (chan_t2_rready),
    .chan_t4_wdata  (chan_t4_prod0_consumer0_wdata),
    .chan_t4_wvalid (chan_t4_prod0_consumer0_wvalid),
    .chan_t4_wready (chan_t4_prod0_consumer0_wready)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:238:5
  main__proc_consumer1 consumer1_inst1 (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:239:5
    .clk            (clk),
    .rst            (rst),
    .chan_t3_rdata  (chan_t3_rdata),
    .chan_t3_rvalid (chan_t3_rvalid),
    .chan_t3_rready (chan_t3_rready),
    .chan_t4_wdata  (chan_t4_prod1_consumer1_wdata),
    .chan_t4_wvalid (chan_t4_prod1_consumer1_wvalid),
    .chan_t4_wready (chan_t4_prod1_consumer1_wready)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:239:5
  main__proc_producer0 producer0_inst2 (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:240:5
    .clk            (clk),
    .rst            (rst),
    .chan_t0_wdata  (chan_t0_wdata),
    .chan_t0_wvalid (chan_t0_wvalid),
    .chan_t0_wready (chan_t0_wready),
    .chan_t4_wdata  (chan_t4_prod3_producer0_wdata),
    .chan_t4_wvalid (chan_t4_prod3_producer0_wvalid),
    .chan_t4_wready (chan_t4_prod3_producer0_wready)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:240:5
  main__proc_producer1 producer1_inst3 (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:241:5
    .clk            (clk),
    .rst            (rst),
    .chan_t1_wdata  (chan_t1_wdata),
    .chan_t1_wvalid (chan_t1_wvalid),
    .chan_t1_wready (chan_t1_wready),
    .chan_t4_wdata  (chan_t4_prod4_producer1_wdata),
    .chan_t4_wvalid (chan_t4_prod4_producer1_wvalid),
    .chan_t4_wready (chan_t4_prod4_producer1_wready)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:241:5
  main__proc_router router_inst4 (	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:242:5
    .clk            (clk),
    .rst            (rst),
    .chan_t0_rdata  (chan_t0_rdata),
    .chan_t0_rvalid (chan_t0_rvalid),
    .chan_t0_rready (chan_t0_rready),
    .chan_t1_rdata  (chan_t1_rdata),
    .chan_t1_rvalid (chan_t1_rvalid),
    .chan_t1_rready (chan_t1_rready),
    .chan_t2_wdata  (chan_t2_wdata),
    .chan_t2_wvalid (chan_t2_wvalid),
    .chan_t2_wready (chan_t2_wready),
    .chan_t3_wdata  (chan_t3_wdata),
    .chan_t3_wvalid (chan_t3_wvalid),
    .chan_t3_wready (chan_t3_wready),
    .chan_t4_wdata  (chan_t4_prod2_router_wdata),
    .chan_t4_wvalid (chan_t4_prod2_router_wvalid),
    .chan_t4_wready (chan_t4_prod2_router_wready)
  );	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:242:5
endmodule

module main__proc_consumer0(	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:38
               rst,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:52
  inout [31:0] chan_t2_rdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:69
  inout        chan_t2_rvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:97
               chan_t2_rready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:125
               chan_t4_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:153
               chan_t4_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:180
               chan_t4_wready	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:245:208
);

  reg  [3:0]  state_reg82;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:265:20
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:266:5
    state_reg82 = 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:256:14, :267:7
  reg  [31:0] recv_reg84;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:270:19
  reg  [31:0] print_reg86;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:272:20
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:274:5
    print_reg86 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:273:17, :275:7
  reg  [31:0] print_reg88;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:277:20
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:279:5
    print_reg88 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:278:17, :280:7
  reg  [31:0] print_reg90;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:282:20
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:284:5
    print_reg90 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:283:17, :285:7
  reg  [31:0] print_reg92;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:287:20
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:289:5
    print_reg92 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:288:17, :290:7
  reg  [31:0] phi_reg94;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:292:18
  wire        _GEN = state_reg82 == 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:259:14, :269:10, :302:11
  assign chan_t4_wvalid = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:302:11, :304:5
  assign chan_t4_wdata = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:302:11, :306:5
  assign chan_t2_rready = state_reg82 == 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:262:14, :269:10, :303:11, :308:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:311:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:312:7
      state_reg82 <= 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:256:14, :313:9
    else begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:312:7
      case (state_reg82)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:269:10, :315:9
        4'b0000: begin
          state_reg82 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:257:14, :317:11
          phi_reg94 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:249:15, :318:11
        end
        4'b0001: begin
          if (phi_reg94 < 32'h4)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:253:15, :293:10, :294:10, :321:11
            state_reg82 <= 4'h5;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:261:14, :322:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:321:11
            state_reg82 <= 4'h2;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:258:14, :324:13
        end
        4'b0010:
          state_reg82 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:259:14, :328:11
        4'b0011: begin
          if (chan_t4_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:307:11, :331:11
            state_reg82 <= 4'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:260:14, :332:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:331:11
            state_reg82 <= state_reg82;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:269:10, :334:13
        end
        4'b0100:
          state_reg82 <= 4'h8;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:264:15, :338:11
        4'b0101:
          state_reg82 <= 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:262:14, :341:11
        4'b0110: begin
          if (chan_t2_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:309:11, :344:11
            recv_reg84 <= chan_t2_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:310:11, :345:13
            state_reg82 <= 4'h7;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:263:14, :346:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:344:11
            state_reg82 <= state_reg82;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:269:10, :348:13
        end
        4'b0111: begin
          print_reg86 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:250:17, :352:11
          print_reg88 = recv_reg84 >> 32'h18 & 32'hFF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:254:16, :255:19, :271:10, :295:10, :296:10, :354:11
          print_reg90 = recv_reg84 >> 32'h10 & 32'hFF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:246:16, :247:17, :271:10, :297:10, :298:10, :356:11
          print_reg92 = recv_reg84 & 32'hFFFF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:248:19, :271:10, :299:10, :358:11
          $write("consumer %0d got src=%0d dest=%0d payload=%0d\n",
                  print_reg86, print_reg88, print_reg90, print_reg92);	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:301:25, :353:17, :355:17, :357:17, :359:17, :360:11
          state_reg82 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:257:14, :361:11
          phi_reg94 <= phi_reg94 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:251:15, :293:10, :300:10, :362:11
        end
        4'b1000:
          state_reg82 <= state_reg82;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:269:10, :365:11
        default:
          state_reg82 <= state_reg82;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:269:10, :368:11
      endcase	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:269:10, :315:9
    end
  end // always @(posedge)
endmodule

module main__proc_consumer1(	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:38
               rst,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:52
  inout [31:0] chan_t3_rdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:69
  inout        chan_t3_rvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:97
               chan_t3_rready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:125
               chan_t4_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:153
               chan_t4_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:180
               chan_t4_wready	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:374:208
);

  reg  [3:0]  state_reg134;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:394:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:395:5
    state_reg134 = 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:385:14, :396:7
  reg  [31:0] recv_reg136;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:399:20
  reg  [31:0] print_reg138;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:401:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:403:5
    print_reg138 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:402:17, :404:7
  reg  [31:0] print_reg140;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:406:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:408:5
    print_reg140 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:407:17, :409:7
  reg  [31:0] print_reg142;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:411:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:413:5
    print_reg142 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:412:17, :414:7
  reg  [31:0] print_reg144;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:416:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:418:5
    print_reg144 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:417:17, :419:7
  reg  [31:0] phi_reg146;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:421:19
  wire        _GEN = state_reg134 == 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:388:14, :398:10, :431:11
  assign chan_t4_wvalid = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:431:11, :433:5
  assign chan_t4_wdata = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:431:11, :435:5
  assign chan_t3_rready = state_reg134 == 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:391:14, :398:10, :432:11, :437:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:440:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:441:7
      state_reg134 <= 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:385:14, :442:9
    else begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:441:7
      case (state_reg134)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:398:10, :444:9
        4'b0000: begin
          state_reg134 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:386:14, :446:11
          phi_reg146 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:375:15, :447:11
        end
        4'b0001: begin
          if (phi_reg146 < 32'h4)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:376:15, :422:10, :423:10, :450:11
            state_reg134 <= 4'h5;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:390:14, :451:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:450:11
            state_reg134 <= 4'h2;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:387:14, :453:13
        end
        4'b0010:
          state_reg134 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:388:14, :457:11
        4'b0011: begin
          if (chan_t4_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:436:11, :460:11
            state_reg134 <= 4'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:389:14, :461:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:460:11
            state_reg134 <= state_reg134;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:398:10, :463:13
        end
        4'b0100:
          state_reg134 <= 4'h8;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:393:15, :467:11
        4'b0101:
          state_reg134 <= 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:391:14, :470:11
        4'b0110: begin
          if (chan_t3_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:438:11, :473:11
            recv_reg136 <= chan_t3_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:439:11, :474:13
            state_reg134 <= 4'h7;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:392:14, :475:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:473:11
            state_reg134 <= state_reg134;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:398:10, :477:13
        end
        4'b0111: begin
          print_reg138 = 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:382:15, :481:11
          print_reg140 = recv_reg136 >> 32'h18 & 32'hFF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:377:16, :378:17, :400:10, :424:10, :425:10, :483:11
          print_reg142 = recv_reg136 >> 32'h10 & 32'hFF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:379:16, :380:19, :400:10, :426:10, :427:10, :485:11
          print_reg144 = recv_reg136 & 32'hFFFF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:381:19, :400:10, :428:10, :487:11
          $write("consumer %0d got src=%0d dest=%0d payload=%0d\n",
                  print_reg138, print_reg140, print_reg142, print_reg144);	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:430:25, :482:17, :484:17, :486:17, :488:17, :489:11
          state_reg134 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:386:14, :490:11
          phi_reg146 <= phi_reg146 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:383:17, :422:10, :429:10, :491:11
        end
        4'b1000:
          state_reg134 <= state_reg134;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:398:10, :494:11
        default:
          state_reg134 <= state_reg134;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:398:10, :497:11
      endcase	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:398:10, :444:9
    end
  end // always @(posedge)
endmodule

module main__proc_producer0(	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:38
               rst,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:52
  inout [31:0] chan_t0_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:69
  inout        chan_t0_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:97
               chan_t0_wready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:125
               chan_t4_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:153
               chan_t4_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:180
               chan_t4_wready	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:208
);

  reg  [3:0]  state_reg185;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:522:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:523:5
    state_reg185 = 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:513:14, :524:7
  reg  [31:0] print_reg187;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:527:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:529:5
    print_reg187 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:528:17, :530:7
  reg  [31:0] print_reg189;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:532:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:534:5
    print_reg189 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:533:17, :535:7
  reg  [31:0] print_reg191;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:537:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:539:5
    print_reg191 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:538:17, :540:7
  reg  [31:0] phi_reg193;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:542:19
  wire [31:0] _GEN = phi_reg193 & 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:506:15, :543:10, :545:10
  wire        _GEN_0 = state_reg185 == 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:516:14, :526:10, :551:10
  assign chan_t0_wvalid = state_reg185 == 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:519:14, :526:10, :552:10, :553:5
  assign chan_t0_wdata = chan_t0_wvalid ? _GEN << 32'h10 | phi_reg193 & 32'hFFFF : 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:503:97, :507:16, :509:19, :543:10, :545:10, :546:10, :547:10, :548:10, :554:17, :555:11, :556:5
  assign chan_t4_wvalid = _GEN_0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:551:10, :558:5
  assign chan_t4_wdata = _GEN_0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:551:10, :560:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:562:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:563:7
      state_reg185 <= 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:513:14, :564:9
    else begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:563:7
      case (state_reg185)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:526:10, :566:9
        4'b0000: begin
          state_reg185 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:514:14, :568:11
          phi_reg193 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:504:15, :569:11
        end
        4'b0001: begin
          if (phi_reg193 < 32'h4)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:505:15, :543:10, :544:10, :572:11
            state_reg185 <= 4'h5;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:518:14, :573:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:572:11
            state_reg185 <= 4'h2;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:515:14, :575:13
        end
        4'b0010:
          state_reg185 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:516:14, :579:11
        4'b0011: begin
          if (chan_t4_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:561:11, :582:11
            state_reg185 <= 4'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:517:14, :583:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:582:11
            state_reg185 <= state_reg185;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:526:10, :585:13
        end
        4'b0100:
          state_reg185 <= 4'h8;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:521:15, :589:11
        4'b0101:
          state_reg185 <= 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:519:14, :592:11
        4'b0110: begin
          if (chan_t0_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:557:11, :595:11
            state_reg185 <= 4'h7;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:520:14, :596:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:595:11
            state_reg185 <= state_reg185;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:526:10, :598:13
        end
        4'b0111: begin
          print_reg187 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:510:17, :602:11
          print_reg189 = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:545:10, :604:11
          print_reg191 = phi_reg193;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:543:10, :606:11
          $write("producer %0d sent dest=%0d payload=%0d\n", print_reg187,
                  print_reg189, print_reg191);	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:550:25, :603:17, :605:17, :607:17, :608:11
          state_reg185 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:514:14, :609:11
          phi_reg193 <= phi_reg193 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:511:17, :543:10, :549:10, :610:11
        end
        4'b1000:
          state_reg185 <= state_reg185;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:526:10, :613:11
        default:
          state_reg185 <= state_reg185;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:526:10, :616:11
      endcase	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:526:10, :566:9
    end
  end // always @(posedge)
endmodule

module main__proc_producer1(	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:38
               rst,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:52
  inout [31:0] chan_t1_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:69
  inout        chan_t1_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:97
               chan_t1_wready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:125
               chan_t4_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:153
               chan_t4_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:180
               chan_t4_wready	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:208
);

  reg  [3:0]  state_reg234;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:643:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:644:5
    state_reg234 = 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:634:14, :645:7
  reg  [31:0] print_reg236;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:648:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:650:5
    print_reg236 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:649:17, :651:7
  reg  [31:0] print_reg238;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:653:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:655:5
    print_reg238 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:654:17, :656:7
  reg  [31:0] print_reg240;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:658:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:660:5
    print_reg240 = 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:659:17, :661:7
  reg  [31:0] phi_reg242;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:663:19
  wire [31:0] _GEN = phi_reg242 + 32'h1 & 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:632:17, :633:17, :664:10, :666:10, :667:10
  wire [31:0] _GEN_0 = phi_reg242 + 32'hA;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:623:16, :664:10, :668:10
  wire        _GEN_1 = state_reg234 == 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:637:14, :647:10, :675:11
  assign chan_t1_wvalid = state_reg234 == 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:640:14, :647:10, :676:11, :677:5
  assign chan_t1_wdata =
    chan_t1_wvalid ? _GEN << 32'h10 | 32'h1000000 | _GEN_0 & 32'hFFFF : 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:622:97, :624:16, :625:22, :626:19, :667:10, :668:10, :669:10, :670:10, :671:10, :672:10, :678:17, :679:11, :680:5
  assign chan_t4_wvalid = _GEN_1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:675:11, :682:5
  assign chan_t4_wdata = _GEN_1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:675:11, :684:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:686:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:687:7
      state_reg234 <= 4'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:634:14, :688:9
    else begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:687:7
      case (state_reg234)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:647:10, :690:9
        4'b0000: begin
          state_reg234 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:635:14, :692:11
          phi_reg242 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:630:15, :693:11
        end
        4'b0001: begin
          if (phi_reg242 < 32'h4)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:631:15, :664:10, :665:10, :696:11
            state_reg234 <= 4'h5;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:639:14, :697:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:696:11
            state_reg234 <= 4'h2;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:636:14, :699:13
        end
        4'b0010:
          state_reg234 <= 4'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:637:14, :703:11
        4'b0011: begin
          if (chan_t4_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:685:11, :706:11
            state_reg234 <= 4'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:638:14, :707:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:706:11
            state_reg234 <= state_reg234;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:647:10, :709:13
        end
        4'b0100:
          state_reg234 <= 4'h8;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:642:15, :713:11
        4'b0101:
          state_reg234 <= 4'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:640:14, :716:11
        4'b0110: begin
          if (chan_t1_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:681:11, :719:11
            state_reg234 <= 4'h7;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:641:14, :720:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:719:11
            state_reg234 <= state_reg234;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:647:10, :722:13
        end
        4'b0111: begin
          print_reg236 = 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:627:15, :726:11
          print_reg238 = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:667:10, :728:11
          print_reg240 = _GEN_0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:668:10, :730:11
          $write("producer %0d sent dest=%0d payload=%0d\n", print_reg236,
                  print_reg238, print_reg240);	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:674:25, :727:17, :729:17, :731:17, :732:11
          state_reg234 <= 4'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:635:14, :733:11
          phi_reg242 <= phi_reg242 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:628:17, :664:10, :673:11, :734:11
        end
        4'b1000:
          state_reg234 <= state_reg234;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:647:10, :737:11
        default:
          state_reg234 <= state_reg234;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:647:10, :740:11
      endcase	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:647:10, :690:9
    end
  end // always @(posedge)
endmodule

module main__proc_router(	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:3
  input        clk,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:35
               rst,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:49
  inout [31:0] chan_t0_rdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:66
  inout        chan_t0_rvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:94
               chan_t0_rready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:122
  inout [31:0] chan_t1_rdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:150
  inout        chan_t1_rvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:178
               chan_t1_rready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:206
  inout [31:0] chan_t2_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:234
  inout        chan_t2_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:262
               chan_t2_wready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:290
  inout [31:0] chan_t3_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:318
  inout        chan_t3_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:346
               chan_t3_wready,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:374
               chan_t4_wdata,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:402
               chan_t4_wvalid,	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:429
               chan_t4_wready	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:746:457
);

  reg  [4:0]  state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:784:21
  initial	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:785:5
    state_reg302 = 5'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:759:14, :786:7
  reg  [31:0] recv_reg304;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:789:20
  reg  [31:0] recv_reg306;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:791:20
  reg  [31:0] phi_reg308;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:793:19
  wire        _GEN = state_reg302 == 5'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:762:14, :788:10, :805:11
  wire        _GEN_0 = state_reg302 == 5'h9;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:768:14, :788:10, :806:11
  wire        _GEN_1 = state_reg302 == 5'hC;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:771:15, :788:10, :807:11
  wire        _GEN_2 = state_reg302 == 5'h12;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:777:16, :788:10, :808:11
  wire        _GEN_3 = state_reg302 == 5'h15;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:780:16, :788:10, :809:11
  assign chan_t2_wvalid = _GEN_1 | _GEN_3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:807:11, :809:11, :812:11, :813:5
  assign chan_t2_wdata = _GEN_1 ? recv_reg304 : _GEN_3 ? recv_reg306 : 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:790:10, :792:10, :807:11, :809:11, :814:17, :815:11, :816:11, :817:5
  assign chan_t3_wvalid = _GEN_0 | _GEN_2;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:806:11, :808:11, :819:11, :820:5
  assign chan_t3_wdata = _GEN_0 ? recv_reg304 : _GEN_2 ? recv_reg306 : 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:790:10, :792:10, :806:11, :808:11, :821:17, :822:11, :823:11, :824:5
  assign chan_t4_wvalid = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:805:11, :826:5
  assign chan_t4_wdata = _GEN;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:805:11, :828:5
  assign chan_t0_rready = state_reg302 == 5'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:765:14, :788:10, :810:11, :830:5
  assign chan_t1_rready = state_reg302 == 5'hF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:774:15, :788:10, :811:11, :833:5
  always @(posedge clk) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:836:5
    if (rst)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:837:7
      state_reg302 <= 5'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:759:14, :838:9
    else begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:837:7
      case (state_reg302)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :840:9
        5'b00000: begin
          state_reg302 <= 5'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:760:14, :842:11
          phi_reg308 <= 32'h0;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:747:15, :843:11
        end
        5'b00001: begin
          if (phi_reg308 < 32'h4)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:748:15, :794:10, :795:10, :846:11
            state_reg302 <= 5'h5;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:764:14, :847:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:846:11
            state_reg302 <= 5'h2;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:761:14, :849:13
        end
        5'b00010:
          state_reg302 <= 5'h3;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:762:14, :853:11
        5'b00011: begin
          if (chan_t4_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:829:11, :856:11
            state_reg302 <= 5'h4;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:763:14, :857:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:856:11
            state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :859:13
        end
        5'b00100:
          state_reg302 <= 5'h18;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:783:15, :863:11
        5'b00101:
          state_reg302 <= 5'h6;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:765:14, :866:11
        5'b00110: begin
          if (chan_t0_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:831:11, :869:11
            recv_reg304 <= chan_t0_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:832:11, :870:13
            state_reg302 <= 5'h7;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:766:14, :871:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:869:11
            state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :873:13
        end
        5'b00111: begin
          if ((recv_reg304 >> 32'h10 & 32'hFF & 32'h1) == 32'h0)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:749:16, :750:17, :751:15, :752:17, :790:10, :796:10, :797:10, :798:10, :799:10, :877:11
            state_reg302 <= 5'hB;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:770:15, :878:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:877:11
            state_reg302 <= 5'h8;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:767:14, :880:13
        end
        5'b01000:
          state_reg302 <= 5'h9;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:768:14, :884:11
        5'b01001: begin
          if (chan_t3_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:825:11, :887:11
            state_reg302 <= 5'hA;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:769:15, :888:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:887:11
            state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :890:13
        end
        5'b01010:
          state_reg302 <= 5'hE;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:773:15, :894:11
        5'b01011:
          state_reg302 <= 5'hC;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:771:15, :897:11
        5'b01100: begin
          if (chan_t2_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:818:11, :900:11
            state_reg302 <= 5'hD;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:772:15, :901:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:900:11
            state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :903:13
        end
        5'b01101:
          state_reg302 <= 5'hE;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:773:15, :907:11
        5'b01110:
          state_reg302 <= 5'hF;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:774:15, :910:11
        5'b01111: begin
          if (chan_t1_rvalid) begin	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:834:11, :913:11
            recv_reg306 <= chan_t1_rdata;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:835:11, :914:13
            state_reg302 <= 5'h10;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:775:16, :915:13
          end
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:913:11
            state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :917:13
        end
        5'b10000: begin
          if ((recv_reg306 >> 32'h10 & 32'hFF & 32'h1) == 32'h0)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:754:18, :755:19, :756:17, :757:17, :792:10, :800:10, :801:11, :802:11, :803:11, :921:11
            state_reg302 <= 5'h14;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:779:16, :922:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:921:11
            state_reg302 <= 5'h11;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:776:16, :924:13
        end
        5'b10001:
          state_reg302 <= 5'h12;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:777:16, :928:11
        5'b10010: begin
          if (chan_t3_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:825:11, :931:11
            state_reg302 <= 5'h13;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:778:16, :932:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:931:11
            state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :934:13
        end
        5'b10011:
          state_reg302 <= 5'h17;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:782:15, :938:11
        5'b10100:
          state_reg302 <= 5'h15;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:780:16, :941:11
        5'b10101: begin
          if (chan_t2_wready)	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:818:11, :944:11
            state_reg302 <= 5'h16;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:781:16, :945:13
          else	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:944:11
            state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :947:13
        end
        5'b10110:
          state_reg302 <= 5'h17;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:782:15, :951:11
        5'b10111: begin
          state_reg302 <= 5'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:760:14, :954:11
          phi_reg308 <= phi_reg308 + 32'h1;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:758:17, :794:10, :804:11, :955:11
        end
        5'b11000:
          state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :958:11
        default:
          state_reg302 <= state_reg302;	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :961:11
      endcase	// /home/qinkejiu/mygo/tests/stages/router_csp/.mygo-tmp/.mygo-circt-3439644373/design.pipeline.mlir:788:10, :840:9
    end
  end // always @(posedge)
endmodule


module mygo_fifo #(
  parameter integer DATA_WIDTH = 32,
  parameter integer DEPTH = 1,
  parameter integer ADDR_WIDTH = 1,
  parameter integer COUNT_WIDTH = 1,
  parameter integer LAST_PTR_VALUE = 0,
  parameter integer DEPTH_COUNT_VALUE = 1,
  parameter integer ALMOST_FULL_LEVEL = 1,
  parameter integer ALMOST_EMPTY_LEVEL = 0,
  parameter integer ALMOST_FULL_COUNT_VALUE = 1,
  parameter integer ALMOST_EMPTY_COUNT_VALUE = 0,
  parameter bit USE_REGISTERED_READ = 1'b0,
  parameter bit ALMOST_EMPTY_USES_EMPTY = 1'b1,
  parameter bit ASYNC_RESET = 1'b0
) (
  input  wire                   clk,
  input  wire                   rst_n,
  input  wire                   wr_en,
  input  wire [DATA_WIDTH-1:0]  wr_data,
  output wire                   full,
  output wire                   almost_full,
  input  wire                   rd_en,
  output wire [DATA_WIDTH-1:0]  rd_data,
  output wire                   empty,
  output wire                   almost_empty
);

  localparam [ADDR_WIDTH-1:0] LAST_PTR = ADDR_WIDTH'(LAST_PTR_VALUE);
  localparam [COUNT_WIDTH-1:0] DEPTH_COUNT = COUNT_WIDTH'(DEPTH_COUNT_VALUE);
  localparam [COUNT_WIDTH-1:0] ALMOST_FULL_COUNT = COUNT_WIDTH'(ALMOST_FULL_COUNT_VALUE);
  localparam [COUNT_WIDTH-1:0] ALMOST_EMPTY_COUNT = COUNT_WIDTH'(ALMOST_EMPTY_COUNT_VALUE);

  reg [DATA_WIDTH-1:0] mem [0:DEPTH-1];
  reg [ADDR_WIDTH-1:0] wr_ptr;
  reg [ADDR_WIDTH-1:0] rd_ptr;
  reg [COUNT_WIDTH-1:0] count;

  wire wr_fire = wr_en && !full;
  wire rd_fire = rd_en && !empty;
  wire [ADDR_WIDTH-1:0] wr_ptr_next = (wr_ptr == LAST_PTR) ? {ADDR_WIDTH{1'b0}} : (wr_ptr + 1'b1);
  wire [ADDR_WIDTH-1:0] rd_ptr_next = (rd_ptr == LAST_PTR) ? {ADDR_WIDTH{1'b0}} : (rd_ptr + 1'b1);

  assign full = (count == DEPTH_COUNT);
  assign empty = (count == {COUNT_WIDTH{1'b0}});
  assign almost_full = (count >= ALMOST_FULL_COUNT);
  assign almost_empty = (ALMOST_EMPTY_USES_EMPTY != 1'b0) ? empty : (count <= ALMOST_EMPTY_COUNT);

  generate
    if (USE_REGISTERED_READ != 1'b0) begin : gen_registered_read
      reg [DATA_WIDTH-1:0] rd_data_reg;
      assign rd_data = empty ? {DATA_WIDTH{1'b0}} : rd_data_reg;

      if (ASYNC_RESET != 1'b0) begin : gen_async_reset
        always @(posedge clk or negedge rst_n) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
            rd_data_reg <= {DATA_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
            if (empty && wr_fire) begin
              rd_data_reg <= wr_data;
            end else if (rd_fire) begin
              if (count > 1) begin
                rd_data_reg <= mem[rd_ptr_next];
              end else if (wr_fire) begin
                rd_data_reg <= wr_data;
              end else begin
                rd_data_reg <= {DATA_WIDTH{1'b0}};
              end
            end else if (!empty) begin
              rd_data_reg <= mem[rd_ptr];
            end
          end
        end
      end else begin : gen_sync_reset
        always @(posedge clk) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
            rd_data_reg <= {DATA_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
            if (empty && wr_fire) begin
              rd_data_reg <= wr_data;
            end else if (rd_fire) begin
              if (count > 1) begin
                rd_data_reg <= mem[rd_ptr_next];
              end else if (wr_fire) begin
                rd_data_reg <= wr_data;
              end else begin
                rd_data_reg <= {DATA_WIDTH{1'b0}};
              end
            end else if (!empty) begin
              rd_data_reg <= mem[rd_ptr];
            end
          end
        end
      end
    end else begin : gen_direct_read
      assign rd_data = empty ? {DATA_WIDTH{1'b0}} : mem[rd_ptr];

      if (ASYNC_RESET != 1'b0) begin : gen_async_reset
        always @(posedge clk or negedge rst_n) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
          end
        end
      end else begin : gen_sync_reset
        always @(posedge clk) begin
          if (!rst_n) begin
            wr_ptr <= {ADDR_WIDTH{1'b0}};
            rd_ptr <= {ADDR_WIDTH{1'b0}};
            count <= {COUNT_WIDTH{1'b0}};
          end else begin
            if (wr_fire) begin
              mem[wr_ptr] <= wr_data;
              wr_ptr <= wr_ptr_next;
            end
            if (rd_fire) begin
              rd_ptr <= rd_ptr_next;
            end
            case ({wr_fire, rd_fire})
              2'b10: count <= count + 1'b1;
              2'b01: count <= count - 1'b1;
              default: count <= count;
            endcase
          end
        end
      end
    end
  endgenerate
endmodule

// mygo autogenerated loop FSM fallback modules
module main__proc_main__loop0_fsm(
  input clk,
        rst,
        check_cond,
        body_done,
        update_done,
  output reg [1:0] state,
  output     active,
             done,
             body_enable,
             update_enable,
             state_check,
             state_body,
             state_update,
             state_exit
);

  // Derived from IR loop condition signal: t19_120
  localparam [1:0] STATE_CHECK  = 2'd0;
  localparam [1:0] STATE_BODY   = 2'd1;
  localparam [1:0] STATE_UPDATE = 2'd2;
  localparam [1:0] STATE_EXIT   = 2'd3;

  // Predecoded state predicates keep control fanout shallow for improved timing closure.
  wire state_is_check = (state == STATE_CHECK);
  wire state_is_body = (state == STATE_BODY);
  wire state_is_update = (state == STATE_UPDATE);
  wire state_is_exit = (state == STATE_EXIT);

  assign state_check = state_is_check;
  assign state_body = state_is_body;
  assign state_update = state_is_update;
  assign state_exit = state_is_exit;
  assign body_enable = state_is_body;
  assign update_enable = state_is_update;
  assign active = ~state_is_exit;
  assign done = state_is_exit;

  // Compact binary state encoding minimizes register usage while keeping timing predictable.
  (* fsm_encoding = "sequential" *) reg [1:0] next_state;

  always @(*) begin
    // Default hold avoids unnecessary state toggles and shortens the transition logic cone.
    next_state = state;
    case (state)
      STATE_CHECK: begin
        if (check_cond)
          next_state = STATE_BODY;
        else
          next_state = STATE_EXIT;
      end
      STATE_BODY: begin
        if (body_done)
          next_state = STATE_UPDATE;
      end
      STATE_UPDATE: begin
        if (update_done)
          next_state = STATE_CHECK;
      end
      STATE_EXIT: begin
        next_state = STATE_EXIT;
      end
      default:
        next_state = STATE_CHECK;
    endcase
  end

  always @(posedge clk) begin
    if (rst)
      state <= STATE_CHECK;
    else
      state <= next_state;
  end
endmodule
